import {env} from 'cloudflare:workers';
import {cookies} from 'next/headers';
import {z} from 'zod';
import {identity,allRecords,checkOrigin,AppError,failure} from '@/lib/server';
import {mailReady} from '@/lib/care-server';
import {googleReady,googleConnection,removeGoogleConnection,seal} from '@/lib/integrations-server';
import {calendarAppointments,calendarIcs} from '@/lib/calendar';
export async function GET(req:Request){try{const a=await identity(req),u=new URL(req.url);if(u.searchParams.has('ics')){const rows=calendarAppointments(await allRecords(a),a);return new Response(calendarIcs(rows,a.tenant),{headers:{'Content-Type':'text/calendar; charset=utf-8','Content-Disposition':'attachment; filename="bem-crescer-agenda.ics"','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}})}const connected=Boolean(await googleConnection(a));return Response.json({googleReady:googleReady(),googleConnected:connected,emailReady:mailReady(),webhookReady:Boolean((env as any).RESEND_WEBHOOK_SECRET),preparationEmailEnabled:(env as any).CARE_TEAM_EMAIL_ENABLED==='true'&&mailReady(),callbackUrl:new URL('/api/integrations/google/callback',req.url).href},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(req:Request){try{checkOrigin(req);const a=await identity(req),x=z.object({action:z.enum(['connectGoogle','disconnectGoogle'])}).parse(await req.json());if(x.action==='disconnectGoogle'){const old=await googleConnection(a);await removeGoogleConnection(a);if(old?.refreshToken)try{await fetch('https://oauth2.googleapis.com/revoke',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:old.refreshToken}),signal:AbortSignal.timeout(10000)})}catch{}return Response.json({ok:true})}
 if(!googleReady())throw new AppError('A clínica ainda precisa de configurar a ligação Google.',503);const state=crypto.randomUUID(),verifier=crypto.randomUUID()+crypto.randomUUID(),challenge=btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const jar=await cookies();jar.set('bc-google-state',await seal({state,verifier,tenant:a.tenant,user:a.user.userId,expires:Date.now()+600000},'google-oauth-state'),{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:600});const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:(env as any).GOOGLE_CLIENT_ID,redirect_uri:new URL('/api/integrations/google/callback',req.url).href,response_type:'code',scope:'https://www.googleapis.com/auth/calendar.events.owned',access_type:'offline',prompt:'consent',state,code_challenge:challenge,code_challenge_method:'S256'}).toString();return Response.json({url:url.href},{headers:{'Cache-Control':'no-store'}});
}catch(e){return failure(e)}}
