import {env} from 'cloudflare:workers';
import {cookies} from 'next/headers';
import {z} from 'zod';
import {identity,allRecords,checkOrigin,AppError,failure} from '@/lib/server';
import {mailProvider,gmailReady,gmailSender,gmailConnection,clinicMailIdentity} from '@/lib/mail-server';
import {googleReady,googleConnection,removeGoogleConnection,seal} from '@/lib/integrations-server';
import {calendarAppointments,calendarIcs} from '@/lib/calendar';
export async function GET(req:Request){try{const a=await identity(req),u=new URL(req.url);if(u.searchParams.has('ics')){const rows=calendarAppointments(await allRecords(a),a);return new Response(calendarIcs(rows,a.tenant),{headers:{'Content-Type':'text/calendar; charset=utf-8','Content-Disposition':'attachment; filename="bem-crescer-agenda.ics"','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}})}const connected=Boolean(await googleConnection(a)),provider=await mailProvider(a);return Response.json({googleReady:googleReady(),googleConnected:connected,gmailReady:gmailReady(),gmailConnected:Boolean(await gmailConnection(a)),gmailSender:gmailSender(),emailProvider:provider,emailReady:provider!=='none',webhookReady:provider==='resend'&&Boolean((env as any).RESEND_WEBHOOK_SECRET),preparationEmailEnabled:(env as any).CARE_TEAM_EMAIL_ENABLED==='true'&&provider!=='none',callbackUrl:new URL('/api/integrations/google/callback',req.url).href},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(req:Request){try{checkOrigin(req);const a=await identity(req),x=z.object({action:z.enum(['connectGoogle','disconnectGoogle','connectGmail','disconnectGmail'])}).parse(await req.json()),provider=x.action.endsWith('Gmail')?'gmail':'google';if(provider==='gmail'){if(!a.owner||a.role!=='director')throw new AppError('Só a direção pode autorizar o Gmail da clínica.',403);const owner=await clinicMailIdentity(a);if(owner.user.userId!==a.user.userId)throw new AppError('A conta não pertence à direção desta clínica.',403);}
 if(x.action.startsWith('disconnect')){const old=await googleConnection(a,provider);await removeGoogleConnection(a,provider);if(old?.refreshToken)try{await fetch('https://oauth2.googleapis.com/revoke',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:old.refreshToken}),signal:AbortSignal.timeout(10000)})}catch{}return Response.json({ok:true})}
 if(!googleReady()||(provider==='gmail'&&!gmailReady()))throw new AppError('A clínica ainda precisa de configurar a ligação Google.',503);const state=crypto.randomUUID(),verifier=crypto.randomUUID()+crypto.randomUUID(),challenge=btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const jar=await cookies();jar.set('bc-google-state',await seal({state,verifier,provider,sender:provider==='gmail'?gmailSender():'',tenant:a.tenant,user:a.user.userId,expires:Date.now()+600000},'google-oauth-state'),{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:600});const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:(env as any).GOOGLE_CLIENT_ID,redirect_uri:new URL('/api/integrations/google/callback',req.url).href,response_type:'code',scope:provider==='gmail'?'openid email https://www.googleapis.com/auth/gmail.send':'https://www.googleapis.com/auth/calendar.events.owned',access_type:'offline',prompt:'consent',state,code_challenge:challenge,code_challenge_method:'S256',...(provider==='gmail'?{login_hint:gmailSender()}:{})}).toString();return Response.json({url:url.href},{headers:{'Cache-Control':'no-store'}});
}catch(e){return failure(e)}}
