BEGIN;
SET LOCAL ROLE service_role;
DO $verification$ DECLARE result jsonb; caught boolean:=false; BEGIN
 PERFORM public.linguar_batch('[{"id":"4643d1cf73d86abde8ee9029","args":["postgres-verification","verification","Verification only","2026-10-07T16:00:00Z"]},{"id":"0a88fe9ef577dbbadfcc4fb6","args":["postgres-verification:patient","postgres-verification","patient","{\"name\":\"Fictitious test\",\"age\":6,\"therapist\":\"owner-profile\",\"shareAuthorized\":\"Sim\",\"guardianEmail\":\"parent@example.invalid\",\"status\":\"Ativo\"}","verification","2026-10-07T16:00:00Z"]},{"id":"0a88fe9ef577dbbadfcc4fb6","args":["postgres-verification:appointment","postgres-verification","appointment","{\"patientId\":\"patient\",\"therapist\":\"owner-profile\",\"date\":\"2026-10-07\",\"time\":\"09:00\",\"duration\":45,\"status\":\"Esperado\"}","verification","2026-10-07T16:00:00Z"]},{"id":"0a88fe9ef577dbbadfcc4fb6","args":["postgres-verification:plan","postgres-verification","plan","{\"patientId\":\"patient\",\"status\":\"Ativo\",\"goals\":[{\"id\":\"goal\",\"name\":\"Test goal\"}]}","verification","2026-10-07T16:00:00Z"]},{"id":"0a88fe9ef577dbbadfcc4fb6","args":["postgres-verification:proposal","postgres-verification","plan","{\"patientId\":\"patient\",\"status\":\"Por aprovar\",\"basePlanId\":\"plan\",\"basePlanVersion\":1}","verification","2026-10-07T16:00:00Z"]},{"id":"2c24be4ec3141cee2b244147","args":["postgres-verification:grant","postgres-verification","patient","parent@example.invalid",1,"2026-10-07T16:00:00Z","postgres-verification:patient","postgres-verification",1]}]'::jsonb);
 result:=public.linguar_batch('[{"id":"00ffd864f4fa06a17f435be3","args":["postgres-verification:session","postgres-verification","session","{\"patientId\":\"patient\",\"appointmentId\":\"appointment\",\"summary\":\"Test clinical record\",\"internalNote\":\"Internal\",\"mutationId\":\"session-operation\"}","verification","2026-10-07T16:00:00Z","postgres-verification:appointment","postgres-verification",1,"postgres-verification:plan","postgres-verification",1]},{"id":"e569047c43891b6a7d7403a1","args":["2026-10-07T16:00:00Z","postgres-verification:appointment","postgres-verification","postgres-verification:session","session-operation"]},{"id":"785d2aa702d24e1a7c45ce92","args":["postgres-verification:session-notice","postgres-verification","careNotice","{\"patientId\":\"patient\",\"type\":\"session\"}","verification","2026-10-07T16:00:00Z","postgres-verification:session","session-operation"]}]'::jsonb);
 IF NOT (result->0->'meta'->>'changes'='1') THEN RAISE EXCEPTION 'Session was not saved'; END IF;
 IF NOT ((SELECT data::jsonb->>'status' FROM public.records WHERE id='postgres-verification:appointment')='Concluída') THEN RAISE EXCEPTION 'Appointment did not finish'; END IF;
 result:=public.linguar_batch('[{"id":"4a835095a85590b8cf1b63b2","args":["{\"mutationId\":\"stale\"}","2026-10-07T16:00:00Z","postgres-verification:session","postgres-verification",0]},{"id":"785d2aa702d24e1a7c45ce92","args":["postgres-verification:stale-notice","postgres-verification","careNotice","{\"body\":\"Must not exist\"}","verification","2026-10-07T16:00:00Z","postgres-verification:session","stale"]}]'::jsonb);
 IF NOT (result->0->'meta'->>'changes'='0') THEN RAISE EXCEPTION 'Stale write was accepted'; END IF;
 IF NOT (NOT EXISTS(SELECT 1 FROM public.records WHERE id='postgres-verification:stale-notice')) THEN RAISE EXCEPTION 'Stale write left a notification'; END IF;
 PERFORM public.linguar_batch('[{"id":"2d9fecea203e795c9875e171","args":["{\"patientId\":\"patient\",\"status\":\"Ativo\",\"mutationId\":\"revision\"}","2026-10-07T16:00:00Z","postgres-verification:proposal",1,"postgres-verification:plan",1]},{"id":"785d2aa702d24e1a7c45ce92","args":["postgres-verification:snapshot","postgres-verification","planSnapshot","{\"originalPlanId\":\"plan\",\"status\":\"Ativo\"}","verification","2026-10-07T16:00:00Z","postgres-verification:proposal","revision"]},{"id":"e3875410151464e370d3d729","args":["proposal","2026-10-07T16:00:00Z","postgres-verification:plan","postgres-verification:proposal","revision"]}]'::jsonb);
 IF NOT (EXISTS(SELECT 1 FROM public.records WHERE id='postgres-verification:snapshot') AND (SELECT data::jsonb->>'status' FROM public.records WHERE id='postgres-verification:plan')='Substituído') THEN RAISE EXCEPTION 'Plan revision was partial'; END IF;
 PERFORM public.linguar_batch('[{"id":"4a835095a85590b8cf1b63b2","args":["{\"name\":\"Fictitious test\",\"shareAuthorized\":\"Não\",\"guardianEmail\":\"parent@example.invalid\",\"mutationId\":\"revoke\"}","2026-10-07T16:00:00Z","postgres-verification:patient","postgres-verification",1]},{"id":"98d53363f5f2f76a5a9949e4","args":["postgres-verification","patient","postgres-verification:patient","revoke"]}]'::jsonb);
 IF NOT ((SELECT enabled FROM public.family_access WHERE id='postgres-verification:grant')=0) THEN RAISE EXCEPTION 'Consent did not revoke access'; END IF;
 BEGIN PERFORM public.linguar_batch('[{"id":"0a88fe9ef577dbbadfcc4fb6","args":["postgres-verification:rollback","postgres-verification","patient","{\"name\":\"Must not persist\"}","verification","2026-10-07T16:00:00Z"]},{"id":"unknown-query","args":[]}]'::jsonb); EXCEPTION WHEN OTHERS THEN caught:=true; END;
 IF NOT (caught) THEN RAISE EXCEPTION 'Invalid query did not fail'; END IF;
 IF NOT (NOT EXISTS(SELECT 1 FROM public.records WHERE id='postgres-verification:rollback')) THEN RAISE EXCEPTION 'Failed transaction left a patient'; END IF;
END $verification$;
ROLLBACK;
SELECT 'sessions, stale writes, plan revisions, consent revocation and transaction rollback passed' AS verification,
 (SELECT count(*) FROM public.records) AS persistent_patient_data;
