'use client';
import {useEffect,useState,useCallback} from 'react';
import {CalendarDays,House,Target,FileText,MessageCircle,UserRound,ArrowUpRight,Check,Clock,ChevronRight,RefreshCw,LogOut,HeartHandshake} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {lisbonNow} from '@/lib/care';
import './parents.css';
const tabs=[['home','Hoje',House],['agenda','Agenda',CalendarDays],['plan','Acompanhamento',Target],['documents','Documentos',FileText],['messages','Mensagens',MessageCircle],['profile','Perfil',UserRound]] as const;
function demonstration(){const today=lisbonNow().date;return {account:{name:'Família de Leonor',email:'familia@example.invalid'},children:[{access:'demo',name:'Leonor Martins'}],access:'demo',view:{patient:{name:'Leonor Martins',age:6,therapist:'Mariana Alves',specialty:'Terapia da Fala',guardian:'Responsável de demonstração'},appointments:[{id:'demo-ap',date:today,time:'16:00',duration:45,status:'Esperado',context:'Clínica',room:'Sala Girassol',therapist:'Mariana Alves'}],publications:[{id:'demo-s',type:'Sumário',title:'O que trabalhámos na última sessão',body:'Praticámos a comunicação de necessidades em situações do quotidiano, com apoio visual. Leonor participou nas propostas e pediu ajuda quando precisou.\n\nNa próxima sessão vamos retomar estas situações e ajustar os apoios.',date:today,read:false},{id:'demo-p',type:'Plano e objetivos',title:'Comunicar com mais autonomia',body:'Objetivo atual: expressar uma necessidade numa situação familiar.\n\nA terapeuta acompanha a frequência e o tipo de ajuda necessários durante as sessões. A evolução será partilhada nos sumários.',date:today,read:true},{id:'demo-h',type:'Orientações para casa',title:'Dar espaço para pedir ajuda',body:'Numa rotina tranquila, dê tempo para que Leonor expresse o que precisa. Pode oferecer duas opções. Partilhe com a terapeuta o que observou e o que foi difícil.',date:today,read:false}],messages:[],requests:[]}}}
const dateLabel=(s:string)=>s?new Date(s.slice(0,10)+'T12:00').toLocaleDateString('pt-PT',{day:'numeric',month:'long'}):'';
export default function ParentPortal(){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('home'),[demo,setDemo]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[unauthorized,setUnauthorized]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[opened,setOpened]=useState<any>(null),[request,setRequest]=useState<any>(null),[requestBody,setRequestBody]=useState(''),[requestType,setRequestType]=useState('Confirmar presença');
 const load=useCallback(async(access='')=>{setLoading(true);try{const r=await fetch('/api/parents'+(access?'?access='+encodeURIComponent(access):''));const j:any=await r.json();setUnauthorized(r.status===401);if(!r.ok)throw Error(j.error);setData(j);setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{if(new URLSearchParams(location.search).get('demo')==='1'){setDemo(true);setData(demonstration());setLoading(false)}else load()},[load]);
 async function act(x:any){if(demo){setError('Esta demonstração não guarda alterações. Use uma conta autorizada para aceder ao acompanhamento.');return false}setBusy(true);setError('');try{const r=await fetch('/api/parents?access='+encodeURIComponent(data.access),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),...x})});const j:any=await r.json();if(!r.ok)throw Error(j.error);await load(data.access);return true}catch(e:any){setError(e.message);return false}finally{setBusy(false)}}
 const v=data?.view,patient=v?.patient,publications=v?.publications||[],unread=publications.filter((r:any)=>!r.read).length,today=lisbonNow().date;
 const upcoming=(v?.appointments||[]).filter((a:any)=>a.date>=today&&!['Cancelada','Falta','Concluída'].includes(a.status));
 const next=upcoming[0];
 const ordered=[...publications].sort((a:any,b:any)=>b.date.localeCompare(a.date));
 function openPublication(r:any){setOpened(r)}
 function pubCard(r:any){return <button className="parent-publication" key={r.id} onClick={()=>openPublication(r)}><span className="parent-file-icon"><FileText size={20}/></span><span><small>{r.type} · {dateLabel(r.date)}</small><strong>{r.title}</strong><span>{r.body.slice(0,130)}{r.body.length>130?'…':''}</span></span>{!r.read&&<i aria-label="Por ler"/>}<ChevronRight size={18}/></button>}
 function appointment(a:any){return <article className="parent-appointment" key={a.id}><div className="parent-date"><strong>{a.date.slice(8)}</strong><span>{new Date(a.date+'T12:00').toLocaleDateString('pt-PT',{month:'short'})}</span></div><div><h3>{a.time} · {a.context||'Sessão'}</h3><p>{a.therapist} · {a.duration} min</p><small>{a.room} {a.room?'· ':''}{a.status}</small>{a.videoUrl&&<p><a href={a.videoUrl} target="_blank" rel="noreferrer">Entrar na teleconsulta</a></p>}</div>{!['Cancelada','Concluída','Falta'].includes(a.status)&&a.date>=today&&<Button variant="outline" onClick={()=>{setRequest(a);setRequestBody('');setRequestType('Confirmar presença')}}>Responder</Button>}</article>}
 return <div className="parents-app"><aside className="parents-sidebar"><a className="parents-brand" href="/pais"><span aria-hidden="true">BC</span><div>Bem Crescer<small>PARA AS FAMÍLIAS</small></div></a><nav aria-label="Navegação dos pais">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)} aria-current={tab===id?'page':undefined}><Icon size={20}/>{label}{id==='home'&&unread>0&&<b>{unread}</b>}</button>)}</nav><div className="parents-support"><HeartHandshake size={24}/><strong>Um acompanhamento próximo.</strong><p>Um espaço para acompanhar, perguntar e partilhar com a equipa.</p></div></aside><main className="parents-main"><header className="parents-top"><span>Área dos pais <span className="parent-dot">●</span> Acompanhamento clínico</span><div>{!demo&&<Button variant="ghost" aria-label="Atualizar painel" onClick={()=>load(data?.access)}><RefreshCw size={16}/></Button>}<span className="parent-avatar"><UserRound size={20}/></span></div></header>
 {demo&&<div className="parents-notice">Demonstração com dados fictícios · <a href="/pais">Abrir a minha área</a> · <a href="/">Voltar à clínica</a></div>}
 {error&&<div className="parents-error" role="alert">{error}{unauthorized&&<a href="/login?next=/pais" target="_top">Iniciar sessão</a>}</div>}
 {loading&&!data&&<p role="status">A carregar o acompanhamento…</p>}
 {!loading&&!v&&!unauthorized&&<section className="parent-card"><h1>O seu espaço de acompanhamento</h1><p>{'Não existe um acompanhamento ativo associado a esta conta. Peça à clínica para confirmar o email do responsável, a autorização e o acesso ao painel.'}</p><a href="/logout" target="_top">Sair e usar outra conta</a></section>}
 {v&&<>{patient.isTest&&<div className="parents-notice">Acompanhamento de teste · Todos os registos desta ficha são fictícios. As marcações não são consultas reais.</div>}<section className="parents-heading"><div><p className="parent-eyebrow">{new Date().toLocaleDateString('pt-PT',{weekday:'long',day:'numeric',month:'long',timeZone:'Europe/Lisbon'})}</p><h1>{tab==='home'?'Estamos consigo.':tabs.find(t=>t[0]===tab)?.[1]}</h1><p>{tab==='home'?'O acompanhamento de '+patient.name+', num só lugar.':'Informação partilhada pela equipa que acompanha '+patient.name+'.'}</p></div>{data.children.length>1&&<Select value={data.access} onValueChange={value=>{setOpened(null);setRequest(null);setMessage('');load(value)}}><SelectTrigger aria-label="Escolher filho" className="w-56"><SelectValue/></SelectTrigger><SelectContent>{data.children.map((c:any)=><SelectItem key={c.access} value={c.access}>{c.name}</SelectItem>)}</SelectContent></Select>}</section>
 {tab==='home'&&<><div className="parents-overview"><section className="parents-child"><span className="parent-eyebrow">O SEU ACOMPANHAMENTO</span><h2>{patient.name}</h2><p>{patient.age===null||patient.age===undefined?'Idade por confirmar':patient.age+' anos'} · {patient.specialty||'Acompanhamento clínico'}</p><div className="parents-therapist"><span className="parent-avatar"><UserRound size={22}/></span><div><small>TERAPEUTA RESPONSÁVEL</small><strong>{patient.therapist}</strong></div><button aria-label="Contactar terapeuta" onClick={()=>setTab('messages')}><ArrowUpRight size={22}/></button></div></section><section className="parent-card parents-next"><span className="parent-eyebrow"><CalendarDays size={15}/> PRÓXIMA SESSÃO</span>{next?<><h2>{dateLabel(next.date)}</h2><p className="parent-next-time">{next.time}<small>{next.duration} minutos · {next.context}</small></p><p>{next.therapist}</p><Button variant="outline" onClick={()=>setTab('agenda')}>Ver marcação <ChevronRight size={16}/></Button></>:<><h2>Por agendar</h2><p>As próximas marcações aparecerão aqui.</p></>}</section></div><div className="parents-section-title"><h2>Novidades do acompanhamento</h2><span>{unread} por ler</span></div><section className="parent-card parents-publications">{ordered.slice(0,3).map(pubCard)}{!ordered.length&&<p className="parent-empty">A terapeuta ainda não partilhou conteúdos neste painel.</p>}</section><div className="parents-help-row"><Clock size={18}/><p>Os sumários aparecem quando a terapeuta os revê e partilha. Pode deixar uma observação para a próxima sessão em Mensagens.</p><Button variant="ghost" onClick={()=>setTab('messages')}>Escrever <ArrowUpRight size={16}/></Button></div></>}
 {tab==='agenda'&&<><section className="parent-card"><h2>Marcações</h2>{(v.appointments||[]).map(appointment)}{!v.appointments.length&&<p className="parent-empty">Sem marcações registadas.</p>}</section><section className="parent-card"><h2>Os seus pedidos</h2><p className="parent-caption">Os pedidos são revistos pela clínica. A marcação mantém-se até a equipa confirmar uma alteração.</p>{v.requests.map((r:any)=><article className="parent-request" key={r.id}><strong>{r.type}</strong><small>{dateLabel(r.date)} · {r.status}</small><p>{r.body}</p>{r.response&&<p className="parent-response">Resposta da clínica: {r.response}</p>}</article>)}{!v.requests.length&&<p className="parent-empty">Ainda não enviou pedidos.</p>}</section></>}
 {tab==='plan'&&<>{['Plano e objetivos','Sumário','Orientações para casa'].map(type=><section className="parent-card parents-publications" key={type}><h2>{type==='Sumário'?'Sumários das sessões':type}</h2>{ordered.filter((r:any)=>r.type===type).map(pubCard)}{!ordered.some((r:any)=>r.type===type)&&<p className="parent-empty">Ainda sem conteúdos partilhados nesta secção.</p>}</section>)}</>}
 {tab==='documents'&&<section className="parent-card parents-publications"><h2>Documentos partilhados</h2><p className="parent-caption">Documentos disponibilizados pela equipa para esta família.</p>{ordered.filter((r:any)=>r.type==='Documento'||r.hasFile).map(pubCard)}{!ordered.some((r:any)=>r.type==='Documento'||r.hasFile)&&<p className="parent-empty">Ainda não existem documentos partilhados.</p>}</section>}
 {tab==='messages'&&<section className="parent-card"><h2>Conversa com a equipa</h2><p className="parent-caption">Partilhe observações, dúvidas ou informações para a próxima sessão. As respostas aparecem aqui; este canal não é acompanhado em permanência.</p><div className="parents-conversation">{v.messages.map((m:any)=><article key={m.id} className={'parent-message '+(m.direction==='parent'?'from-parent':'')}><small>{m.direction==='parent'?'Família':'Equipa clínica'} · {dateLabel(m.date)}</small><p>{m.body}</p></article>)}{!v.messages.length&&<p className="parent-empty">Como têm corrido os últimos dias? Pode deixar aqui uma nota para a equipa.</p>}</div><form onSubmit={async e=>{e.preventDefault();if(await act({action:'message',body:message}))setMessage('')}}><label htmlFor="family-message">A sua mensagem</label><Textarea id="family-message" value={message} onChange={e=>setMessage(e.target.value)} maxLength={6000} rows={4} required/><Button disabled={busy||!message.trim()} type="submit">Enviar mensagem <ArrowUpRight size={16}/></Button></form></section>}
 {tab==='profile'&&<section className="parent-card parents-profile"><span className="parent-avatar"><UserRound size={28}/></span><h2>{data.account.name}</h2><p>{data.account.email}</p><dl><dt>Acompanhamento</dt><dd>{patient.name}</dd><dt>Responsável registado</dt><dd>{patient.guardian||'Por confirmar'}</dd><dt>Terapeuta</dt><dd>{patient.therapist}</dd></dl><p className="parent-caption">Para corrigir os seus contactos ou esclarecer autorizações, envie uma mensagem à clínica.</p><Button variant="outline" onClick={()=>setTab('messages')}>Pedir atualização dos dados</Button>{!demo&&<a href="/logout" target="_top"><LogOut size={16}/> Terminar sessão</a>}</section>}
 </>}
 <footer className="parents-footer">Bem Crescer · Clínica, terapeuta e família, em contacto.</footer></main>
 <Dialog open={!!opened} onOpenChange={o=>!o&&setOpened(null)}><DialogContent className="parents-dialog"><DialogHeader><DialogTitle>{opened?.title}</DialogTitle><DialogDescription>{opened?.type} · {dateLabel(opened?.date)}</DialogDescription></DialogHeader>{error&&<p role="alert" className="parents-error">{error}</p>}<p className="parents-full-text">{opened?.body}</p>{opened?.hasFile&&!demo&&<a className="parent-download" href={'/api/parents?access='+encodeURIComponent(data.access)+'&document='+encodeURIComponent(opened.id)}>Descarregar anexo</a>}<Button disabled={busy||opened?.read} onClick={async()=>{if(await act({action:'read',publicationId:opened.id}))setOpened({...opened,read:true})}}><Check size={16}/>{opened?.read?'Leitura confirmada':'Confirmar que li'}</Button></DialogContent></Dialog>
 <Dialog open={!!request} onOpenChange={o=>!o&&setRequest(null)}><DialogContent><DialogHeader><DialogTitle>Responder à marcação</DialogTitle><DialogDescription>{dateLabel(request?.date)} · {request?.time}. A clínica irá rever o seu pedido.</DialogDescription></DialogHeader>{error&&<p role="alert" className="parents-error">{error}</p>}<label>O que pretende?<Select value={requestType} onValueChange={setRequestType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['Confirmar presença','Pedir alteração','Comunicar ausência'].map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></label><label>Nota para a equipa<Textarea value={requestBody} onChange={e=>setRequestBody(e.target.value)} maxLength={6000}/></label><Button disabled={busy} onClick={async()=>{if(await act({action:'request',appointmentId:request.id,type:requestType,body:requestBody}))setRequest(null)}}>Enviar à clínica</Button></DialogContent></Dialog>
 </div>;
}
