import assert from 'node:assert/strict';
import ts from 'typescript';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('../lib/access.ts',import.meta.url),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {visible,mayWrite}=await import('data:text/javascript;base64,'+Buffer.from(compiled).toString('base64'));
const therapist={role:'therapist',therapist:'t1',user:{userId:'u1'}};
const director={role:'director',therapist:'t1',user:{userId:'owner'}};
const rec=(id,kind,data,author='u1')=>({id,kind,data,author,version:1});
const mine=rec('p1','patient',{therapist:'t1'}),other=rec('p2','patient',{therapist:'t2'}),rows=[mine,other];
assert.equal(visible(mine,therapist,rows),true);
assert.equal(visible(other,therapist,rows),false);
assert.equal(visible(rec('s1','session',{patientId:'p2'}),therapist,rows),false);
assert.equal(visible(rec('s2','session',{patientId:'p1'}),therapist,rows),true);
assert.equal(visible(rec('i','invoice',{amount:40}),therapist,rows),false);
assert.equal(visible(rec('f','file',{visibility:'Pessoal'},'someone-else'),director,rows),false);
assert.equal(visible(rec('f','file',{visibility:'Clínica',patientId:'p2'}),therapist,rows),false);
assert.equal(visible(rec('pref','preference',{},'someone-else'),therapist,rows),false);
assert.equal(mayWrite('invoice',therapist),false);
assert.equal(mayWrite('team',therapist),false);
assert.equal(mayWrite('material',therapist),false);
assert.equal(mayWrite('alert',therapist),false);
assert.equal(mayWrite('session',therapist),true);
assert.equal(mayWrite('prescription',therapist),true);
assert.equal(mayWrite('file',director),false);
assert.equal(mayWrite('invoice',director),true);
console.log('16 authorization checks passed');
