import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const compile=p=>ts.transpileModule(fs.readFileSync(new URL('../'+p,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const sqlite=new DatabaseSync(':memory:');for(const name of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync(new URL('../drizzle/'+name,import.meta.url),'utf8'));
const registered=new Set(JSON.parse(fs.readFileSync(new URL('../lib/query-catalog.json',import.meta.url),'utf8')).map(q=>q.sqlite));
const d1={prepare(sql){assert.ok(registered.has(sql.trim().replace(/\s+/g,' ')),'Unregistered server query: '+sql);return {bind(...values){return {async run(){const r=sqlite.prepare(sql).run(...values);return {meta:{changes:Number(r.changes)}}},async all(){return {results:sqlite.prepare(sql).all(...values)}},async first(){return sqlite.prepare(sql).get(...values)||null}}}}},async batch(statements){sqlite.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};
globalThis.familyTest={db:d1,config:{CLINIC_OWNER_EMAIL:'director@example.invalid'},user:{userId:'c',email:'director@example.invalid',displayName:'Direção'}};
const env=url('export const env={DB:globalThis.familyTest.db,BUCKET:{get:async()=>({body:"document bytes"})},get PILOT_ACCOUNTS(){return globalThis.familyTest.config.PILOT_ACCOUNTS},get CLINIC_OWNER_EMAIL(){return globalThis.familyTest.config.CLINIC_OWNER_EMAIL}}'),auth=url('export const currentUser=async()=>globalThis.familyTest.user');
const patientsModule=url(compile('lib/patients.ts'));
const access=url(compile('lib/access.ts')),model=url(compile('lib/model.ts')),care=url(compile('lib/care.ts')),family=url(compile('lib/family.ts').replaceAll("'./patients'",JSON.stringify(patientsModule)).replaceAll("'./care'",JSON.stringify(care)));
const databaseMock=url('export const database=()=>globalThis.familyTest.db');const storageMock=url('export const storage=()=>({get:async()=>({body:"document bytes"})})');
const scope=url(compile('lib/record-scope.ts').replaceAll("'./model'",JSON.stringify(model)));
const server=url(compile('lib/server.ts').replaceAll("'./record-scope'",JSON.stringify(scope)).replaceAll("'./auth'",JSON.stringify(auth)).replaceAll("'./supabase-database'",JSON.stringify(databaseMock)).replaceAll("'./supabase-http'",JSON.stringify(storageMock)).replaceAll("'cloudflare:workers'",JSON.stringify(env)).replaceAll("'@/lib/auth'",JSON.stringify(auth)).replaceAll("'./model'",JSON.stringify(model)).replaceAll("'./access'",JSON.stringify(access)));
const careServer=url(compile('lib/care-server.ts').replaceAll("'cloudflare:workers'",JSON.stringify(env)).replaceAll("'./server'",JSON.stringify(server)).replaceAll("'./care'",JSON.stringify(care)));
const workflows=url(compile('lib/workflows.ts').replaceAll("'./access'",JSON.stringify(access)));
const route=p=>url(compile(p).replaceAll("'@/lib/patients'",JSON.stringify(patientsModule)).replaceAll("'@/lib/access'",JSON.stringify(access)).replaceAll("'cloudflare:workers'",JSON.stringify(env)).replaceAll("'@/lib/workflows'",JSON.stringify(workflows)).replaceAll("'@/lib/model'",JSON.stringify(model)).replaceAll("'zod'",JSON.stringify(pathToFileURL(require.resolve('zod')).href)).replaceAll("'@/lib/server'",JSON.stringify(server)).replaceAll("'@/lib/auth'",JSON.stringify(auth)).replaceAll("'@/lib/family'",JSON.stringify(family)).replaceAll("'@/lib/care'",JSON.stringify(care)).replaceAll("'@/lib/care-server'",JSON.stringify(careServer)));
const pro=await import(route('app/api/family/route.ts')),parent=await import(route('app/api/parents/route.ts')),{identity}=await import(server);
const put=(id,kind,data,clinic='c')=>sqlite.prepare('INSERT OR REPLACE INTO records(id,clinic,kind,data,author,version,updated) VALUES(?,?,?,?,?,1,?)').run(clinic+':'+id,clinic,kind,JSON.stringify(data),'u',new Date().toISOString());
const director=()=>globalThis.familyTest.user={userId:'c',email:'director@example.invalid',displayName:'Direção'};
const guardian=()=>globalThis.familyTest.user={userId:'parent',email:'parent@example.invalid',displayName:'Família'};
const therapist=()=>globalThis.familyTest.user={userId:'therapist',email:'therapist@example.invalid',displayName:'Terapeuta'};
const req=(path,body)=>new Request('https://test.invalid'+path,body?{method:'POST',headers:{'content-type':'application/json','origin':'https://test.invalid'},body:JSON.stringify(body)}:undefined);
const call=async(route,method,path,body)=>{const r=await route[method](req(path,body));return {status:r.status,data:r.headers.get('content-type')?.includes('json')?await r.json():await r.text()}};
const invoke=x=>call(pro,'POST','/api/family',{patientId:'p',...x});
sqlite.prepare('INSERT INTO clinics VALUES(?,?,?,?)').run('c','c','Clínica','now');
put('p','patient',{name:'Paciente autorizado',age:6,guardianEmail:'parent@example.invalid',shareAuthorized:'Sim',therapist:'t1',internalNote:'PRIVATE',diagnosis:'PRIVATE',currentWorld:7,xp:800});
put('q','patient',{name:'PRIVATE_OTHER_CHILD',guardianEmail:'other@example.invalid',shareAuthorized:'Sim',therapist:'t2'});
put('t1','team',{name:'Terapeuta',email:'PRIVATE_EMPLOYEE'});
put('session','session',{patientId:'p',status:'Concluída',summary:'PRIVATE_RAW',internalNote:'PRIVATE_NOTE'});
put('draft','session',{patientId:'p',status:'Rascunho'});
put('file','file',{patientId:'p',name:'relatorio.pdf',key:'c/file',type:'application/pdf'});
put('other-file','file',{patientId:'q',name:'PRIVATE_FILE',key:'c/other'});
const today=new Date().toISOString().slice(0,10);
put('ap','appointment',{patientId:'p',therapist:'t1',date:today,time:'23:00',status:'Esperado',notes:'PRIVATE_APPT'});
put('ap-other','appointment',{patientId:'q',date:today,time:'23:00',status:'Esperado'});
let r=await invoke({action:'grant',email:'wrong@example.invalid',enabled:true});assert.equal(r.status,400);
r=await invoke({action:'grant',email:'parent@example.invalid',enabled:true});assert.equal(r.status,200);
const grant=sqlite.prepare('SELECT id FROM family_access WHERE patient_id=?').get('p').id;
const base={action:'publish',id:'pub',type:'Sumário',title:'Texto para a família',body:'PUBLIC_REVIEWED',sourceId:'session',sourceVersion:1,confirmed:true,fileId:'file'};
assert.equal((await invoke({...base,confirmed:false})).status,400); // validation rejects malformed consent
assert.equal((await invoke({...base,sourceId:'draft'})).status,400);
assert.equal((await invoke({...base,sourceVersion:2})).status,409);
assert.equal((await invoke({...base,fileId:'other-file'})).status,403);
assert.equal((await invoke(base)).status,200);
assert.equal((await invoke(base)).status,409); // no duplicate publication
put('hidden','familyPublication',{patientId:'p',recipient:'other@example.invalid',status:'Publicado',body:'PRIVATE_WRONG_RECIPIENT'});
guardian();r=await call(parent,'GET','/api/parents');assert.equal(r.status,200);assert.equal(r.data.children.length,1);assert.equal(r.data.view.publications.length,1);assert.equal(r.data.view.publications[0].body,'PUBLIC_REVIEWED');assert.equal(JSON.stringify(r.data).includes('PRIVATE'),false);assert.equal(JSON.stringify(r.data).includes('currentWorld'),false);assert.equal(r.data.view.publications[0].hasFile,true);
await assert.rejects(()=>identity(req('/api/data')),e=>e.status===403);
assert.equal((await call(pro,'GET','/api/family?patientId=p')).status,403);
assert.equal((await call(parent,'GET','/api/parents?access=wrong')).status,403);
assert.equal((await call(parent,'GET','/api/parents?access='+grant+'&document=pub')).status,200);
assert.equal((await call(parent,'GET','/api/parents?access='+grant+'&document=hidden')).status,404);
assert.equal((await call(parent,'POST','/api/parents?access='+grant,{action:'message',id:'message',body:'OBSERVAÇÃO_DA_FAMÍLIA',patientId:'q'})).status,200);
const saved=JSON.parse(sqlite.prepare('SELECT data FROM records WHERE id=?').get('c:message').data);assert.equal(saved.patientId,'p');
assert.equal((await call(parent,'POST','/api/parents?access='+grant,{action:'request',id:'wrong-request',appointmentId:'ap-other',type:'Pedir alteração'})).status,400);
assert.equal((await call(parent,'POST','/api/parents?access='+grant,{action:'request',id:'request',appointmentId:'ap',type:'Pedir alteração',body:'Outro horário?'})).status,200);
assert.equal(JSON.parse(sqlite.prepare('SELECT data FROM records WHERE id=?').get('c:ap').data).status,'Esperado');
assert.equal((await call(parent,'POST','/api/parents?access='+grant,{action:'read',id:'read',publicationId:'pub'})).status,200);
r=await call(parent,'GET','/api/parents');assert.equal(r.data.view.publications[0].read,true);
const {preparation}=await import(care),{allRecords}=await import(server);director();const rows=await allRecords(await identity(req('/')));assert.ok(preparation(rows,rows.find(r=>r.id==='ap')).body.includes('OBSERVAÇÃO_DA_FAMÍLIA'));
assert.equal((await invoke({action:'resolve',id:'request',response:'Foi registado o pedido; mantemos o horário.'})).status,200);
assert.equal((await invoke({action:'withdraw',id:'pub'})).status,200);guardian();assert.equal((await call(parent,'GET','/api/parents')).data.view.publications.length,0);assert.equal((await call(parent,'GET','/api/parents?document=pub')).status,404);
director();sqlite.prepare('INSERT INTO memberships(id,clinic,email,therapist) VALUES(?,?,?,?)').run('m','c','therapist@example.invalid','t1');therapist();assert.equal((await invoke({action:'grant',email:'parent@example.invalid',enabled:true})).status,403);assert.equal((await invoke({patientId:'q',action:'message',id:'bad',body:'No'})).status,403);
director();assert.equal((await invoke({action:'grant',email:'parent@example.invalid',enabled:false})).status,200);guardian();assert.equal((await call(parent,'GET','/api/parents')).data.children.length,0);assert.equal((await call(parent,'POST','/api/parents?access='+grant,{action:'message',id:'revoked',body:'No'})).status,403);await assert.rejects(()=>identity(req('/api/data')),e=>e.status===403);
director();await invoke({action:'grant',email:'parent@example.invalid',enabled:true});put('p','patient',{name:'Changed',guardianEmail:'new@example.invalid',shareAuthorized:'Sim',therapist:'t1'});guardian();assert.equal((await call(parent,'GET','/api/parents')).data.children.length,0);
globalThis.familyTest.user=null;assert.equal((await call(parent,'GET','/api/parents')).status,401);
const {visible,mayWrite}=await import(access);assert.equal(visible({kind:'patient'}, {role:'parent'}, []),false);assert.equal(mayWrite('familyPublication',{role:'director'}),false);
console.log('Family portal: access, consent, selective publication, documents, requests, messages, preparation, withdrawal and revocation passed.');

// Full professional -> parent -> next-session circuit, using all real route handlers.
const dataAPI=await import(route('app/api/data/route.ts')),careAPI=await import(route('app/api/care/route.ts')),accessAPI=await import(route('app/api/access/route.ts'));
const pilotOwner=()=>globalThis.familyTest.user={userId:'pilot-c',email:'pilot-owner@example.invalid',displayName:'Direção piloto'};
const pilotTherapist=()=>globalThis.familyTest.user={userId:'pilot-t',email:'pilot-therapist@example.invalid',displayName:'Terapeuta piloto'};
const pilotParent=()=>globalThis.familyTest.user={userId:'pilot-parent',email:'pilot-parent@example.invalid',displayName:'Família piloto'};
const save=async(id,kind,data,version=0)=>call(dataAPI,'POST','/api/data',{id,kind,data,version});
globalThis.familyTest.config.CLINIC_OWNER_EMAIL='pilot-owner@example.invalid';pilotOwner();r=await call(dataAPI,'GET','/api/data');assert.equal(r.status,200);assert.equal(r.data.records.length,1);assert.equal(r.data.records[0].kind,'team');put('t1','team',{name:'Terapeuta distinta',status:'Ativo'},'pilot-c'); // no fictional patients seeded
assert.equal((await save('room','room',{name:'Sala piloto',status:'Disponível',capacity:2})).status,200);
assert.equal((await save('child','patient',{name:'Paciente fictício do teste',age:6,therapist:'t1',guardian:'Responsável fictício',guardianEmail:'pilot-parent@example.invalid',shareAuthorized:'Sim',status:'Ativo'})).status,200);
assert.equal((await call(accessAPI,'POST','/api/access',{therapist:'t1',email:'pilot-therapist@example.invalid',enabled:true})).status,200);
assert.equal((await call(pro,'POST','/api/family',{patientId:'child',action:'grant',email:'pilot-parent@example.invalid',enabled:true})).status,200);
pilotTherapist();
assert.equal((await save('appointment','appointment',{patientId:'child',therapist:'t1',date:today,time:'09:00',duration:45,context:'Clínica',room:'room',status:'Esperado'})).status,200);
const goals=[{id:'goal',name:'Objetivo observado',criteria:'Mesmo contexto com apoio visual',progress:0,status:'Em progresso',targetPercent:80,requiredSessions:2}];
let plan={patientId:'child',name:'Plano de acompanhamento',context:'Clínica',status:'Rascunho',goals};
assert.equal((await save('plan','plan',plan)).status,200);
plan={...plan,status:'Por aprovar'};assert.equal((await save('plan','plan',plan,1)).status,200);
assert.equal((await save('plan','plan',{...plan,status:'Ativo'},2)).status,403);
pilotOwner();plan={...plan,status:'Ativo'};assert.equal((await save('plan','plan',plan,2)).status,200);
pilotTherapist();const sessionInput={action:'session',appointmentId:'appointment',version:0,summary:'Registo clínico do teste.',nextSteps:'Retomar alvo em contexto semelhante.',materials:'Cartões',familySummary:'Resumo revisto para a família.',internalNote:'SECRET_INTERNAL_CIRCUIT',goalResults:[{planId:'plan',goalId:'goal',observed:true,correct:8,help:2,attempts:10,note:'Observação'}],final:false};
r=await call(careAPI,'POST','/api/care',sessionInput);assert.equal(r.status,200);
r=await call(careAPI,'POST','/api/care',{...sessionInput,version:1,final:true});assert.equal(r.status,200);
r=await call(dataAPI,'GET','/api/data');assert.equal(r.data.records.find(r=>r.id==='appointment').data.status,'Concluída');
assert.equal((await call(pro,'POST','/api/family',{patientId:'child',action:'publish',id:'publication',type:'Sumário',title:'Resumo da sessão',body:'Resumo revisto para a família.',sourceId:'care-appointment',sourceVersion:2,confirmed:true})).status,200);
pilotParent();r=await call(parent,'GET','/api/parents');assert.equal(r.status,200);assert.equal(r.data.children.length,1);assert.equal(r.data.view.patient.name,'Paciente fictício do teste');assert.equal(JSON.stringify(r.data).includes('SECRET'),false);assert.equal(r.data.view.publications[0].body,'Resumo revisto para a família.');
const pilotGrant=r.data.access;
assert.equal((await call(parent,'POST','/api/parents?access='+pilotGrant,{action:'read',id:'pilot-read',publicationId:'publication'})).status,200);
assert.equal((await call(parent,'POST','/api/parents?access='+pilotGrant,{action:'message',id:'pilot-message',body:'NOTA_PARA_PROXIMA_SESSAO'})).status,200);
pilotTherapist();const {nextDay}=await import(care);assert.equal((await save('next','appointment',{patientId:'child',therapist:'t1',date:nextDay(today),time:'09:00',duration:45,context:'Clínica',room:'room',status:'Esperado'})).status,200);
assert.equal((await call(careAPI,'POST','/api/care',{action:'refresh'})).status,200);
r=await call(dataAPI,'GET','/api/data');const brief=r.data.records.find(r=>r.kind==='careNotice'&&r.data.type==='brief');assert.ok(brief.data.body.includes('NOTA_PARA_PROXIMA_SESSAO'));assert.ok(brief.data.body.includes('Objetivo observado'));assert.ok(brief.data.body.includes('Retomar alvo'));assert.ok(r.data.records.some(r=>r.kind==='careNotice'&&r.data.name==='Conteúdo lido pelos pais'));
// Revoking a therapist no longer makes the account look like a new director.
pilotOwner();assert.equal((await call(accessAPI,'POST','/api/access',{therapist:'t1',email:'pilot-therapist@example.invalid',enabled:false})).status,200);pilotTherapist();assert.equal((await call(dataAPI,'GET','/api/data')).status,403);
pilotOwner();assert.equal((await call(accessAPI,'POST','/api/access',{therapist:'t1',email:'pilot-therapist@example.invalid',enabled:true})).status,200);pilotTherapist();assert.equal((await call(dataAPI,'GET','/api/data')).status,200);
console.log('Complete clinical circuit passed: clean clinic, account grant, appointment, plan approval, session, parent publication/read/reply, next-day preparation and therapist revocation.');

// Daily professional use: explicitly configured owner and separate staff accounts.
globalThis.familyTest.config.CLINIC_OWNER_EMAIL='clinic-owner@example.invalid';
const realOwner=()=>globalThis.familyTest.user={userId:'real-clinic',email:'clinic-owner@example.invalid',displayName:'Direção real'};
const staff=()=>globalThis.familyTest.user={userId:'real-staff',email:'staff@example.invalid',displayName:'Profissional'};
globalThis.familyTest.user={userId:'unlisted',email:'unlisted@example.invalid',displayName:'Sem associação'};
assert.equal((await call(dataAPI,'GET','/api/data')).status,403);assert.equal(sqlite.prepare('SELECT id FROM clinics WHERE id=?').get('unlisted'),undefined);
realOwner();r=await call(dataAPI,'GET','/api/data');assert.equal(r.data.therapist,'owner-profile');assert.equal(r.data.records.length,1);assert.equal(r.data.records[0].data.isTest,undefined);
const newStaff={therapist:'actual-therapist',email:'staff@example.invalid',enabled:true,profile:{name:'Profissional',specialty:'Psicologia',hours:30,startTime:'09:00',workDays:'1,2,3,4,5'}};
assert.equal((await call(accessAPI,'POST','/api/access',newStaff)).status,200);assert.equal((await call(accessAPI,'POST','/api/access',newStaff)).status,200);
assert.equal(sqlite.prepare('SELECT count(*) AS n FROM memberships WHERE email=?').get(newStaff.email).n,1);
assert.equal((await call(accessAPI,'POST','/api/access',{therapist:'actual-therapist',email:'different@example.invalid',enabled:true})).status,409);
assert.equal(sqlite.prepare('SELECT id FROM memberships WHERE email=?').get('different@example.invalid'),undefined);
assert.equal((await save('assigned','patient',{name:'Paciente atribuído',age:7,therapist:'actual-therapist',status:'Ativo'})).status,200);
assert.equal((await save('not-assigned','patient',{name:'OTHER_PATIENT',age:8,therapist:'owner-profile',status:'Ativo'})).status,200);
put('owner-profile','team',{name:'Direção real',email:'PRIVATE_EMAIL',monthlyHours:140,hours:35,monthlyGoal:80,status:'Ativo'},'real-clinic');
staff();r=await call(dataAPI,'GET','/api/data?view=director');assert.equal(r.data.role,'therapist');assert.equal(r.data.owner,false);assert.ok(r.data.records.some(x=>x.id==='assigned'));assert.equal(JSON.stringify(r.data).includes('OTHER_PATIENT'),false);assert.equal(JSON.stringify(r.data).includes('PRIVATE_EMAIL'),false);assert.equal(r.data.records.find(x=>x.id==='owner-profile').data.monthlyHours,undefined);
assert.equal((await call(accessAPI,'POST','/api/access',{...newStaff,email:'intruder@example.invalid'})).status,403);
assert.equal((await call(accessAPI,'GET','/api/access')).status,403);
assert.equal((await save('hijacked','patient',{name:'No',age:8,therapist:'owner-profile',status:'Ativo'})).status,403);
assert.equal((await save('point','attendance',{name:'Entrada',therapist:'actual-therapist',type:'Entrada'})).status,200);
assert.equal((await save('point-for-other','attendance',{name:'Entrada',therapist:'owner-profile',type:'Entrada'})).status,403);
realOwner();r=await call(accessAPI,'GET','/api/access');assert.ok(r.data.members.find(m=>m.email==='staff@example.invalid').firstAccess);
assert.equal((await save('actual-therapist','team',{...newStaff.profile,email:newStaff.email,status:'Inativo'},1)).status,200);
staff();assert.equal((await call(dataAPI,'GET','/api/data')).status,403);
realOwner();assert.equal((await save('actual-therapist','team',{...newStaff.profile,email:newStaff.email,status:'Ativo'},2)).status,200);
assert.equal((await call(accessAPI,'POST','/api/access',{therapist:'actual-therapist',email:newStaff.email,enabled:false})).status,200);staff();assert.equal((await call(dataAPI,'GET','/api/data')).status,403);
realOwner();assert.equal((await call(accessAPI,'POST','/api/access',{therapist:'actual-therapist',email:newStaff.email,enabled:true})).status,200);staff();assert.equal((await call(dataAPI,'GET','/api/data')).status,200);
const {tagExampleRecords,dailyRecords}=await import(scope),{sampleRecords}=await import(model);
const fixtures=sampleRecords('2026-01-01');fixtures.push({id:'real-profile',kind:'team',version:1,author:'real-account',data:{name:'Real'}},{id:'real-patient',kind:'patient',version:1,author:'real-account',data:{name:'Real',therapist:'real-profile'}},{id:'test-child-note',kind:'session',version:1,author:'real-account',data:{patientId:'p0',summary:'Test'}});
const tagged=tagExampleRecords(fixtures),daily=dailyRecords(tagged);assert.equal(tagged.find(x=>x.id==='test-child-note').data.isTest,true);assert.deepEqual(daily.map(x=>x.id),['real-profile','real-patient']);assert.equal(fixtures.find(x=>x.id==='p0').data.isTest,undefined);
console.log('Daily team access passed: explicit owner, unknown-account denial, atomic staff setup, no shared professional accounts, role isolation, colleague data minimization, first entry, own check-in, inactivation/revocation and example separation.');

// Incomplete imported records remain editable without inventing age or assignment.
realOwner();
const {patientAge}=await import(patientsModule);
for(const age of [undefined,null,'','   '])assert.equal(patientAge({age}),null);
assert.equal(patientAge({age:0}),0);assert.equal(patientAge({age:'6'}),6);
let importedData={name:'Cadastro por completar',age:null,therapist:'',status:'Ativo',guardians:[],notes:'Confirmar dados com a família.',followUpStatus:'Por confirmar'};
r=await save('imported-incomplete','patient',importedData);assert.equal(r.status,200);
assert.equal(r.data.record.data.age,null);assert.equal(r.data.record.data.therapist,'');assert.equal(r.data.record.data.familyId,'imported-incomplete');
importedData={...r.data.record.data,notes:'Informação de origem preservada.'};
r=await save('imported-incomplete','patient',importedData,1);assert.equal(r.status,200);assert.equal(r.data.record.data.followUpStatus,'Por confirmar');assert.equal(r.data.record.data.notes,importedData.notes);
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM family_access WHERE patient_id=?').get('imported-incomplete').n,0);
staff();r=await call(dataAPI,'GET','/api/data');assert.equal(r.data.records.some(x=>x.id==='imported-incomplete'),false);
assert.equal((await save('imported-incomplete','patient',{...importedData,therapist:'actual-therapist'},2)).status,403);
assert.equal((await save('staff-unassigned','patient',{name:'Sem atribuição',age:null,therapist:''})).status,403);
assert.equal((await save('staff-other','patient',{name:'De outro profissional',age:null,therapist:'owner-profile'})).status,403);
assert.equal((await save('staff-own-incomplete','patient',{name:'Cadastro próprio por completar',therapist:'actual-therapist'})).status,200);
realOwner();
for(const [i,age] of [undefined,'','   '].entries()){
 r=await save('missing-age-'+i,'patient',{name:'Idade por preencher '+i,age,therapist:''});assert.equal(r.status,200);assert.equal(r.data.record.data.age,null);
}
for(const [i,age] of [-1,121,'not-a-number',true,[],{},'Infinity','0x10'].entries())assert.equal((await save('invalid-age-'+i,'patient',{name:'Idade inválida '+i,age,therapist:''})).status,400);
r=await save('newborn','patient',{name:'Idade zero confirmada',age:0,therapist:''});assert.equal(r.status,200);assert.equal(r.data.record.data.age,0);
r=await save('numeric-age','patient',{name:'Idade indicada como texto',age:'6',therapist:''});assert.equal(r.status,200);assert.equal(r.data.record.data.age,6);
assert.equal((await save('invalid-assignment','patient',{name:'Atribuição inexistente',therapist:'unknown-therapist'})).status,400);
assert.equal((await save('inactive-profile','team',{name:'Perfil inativo',status:'Inativo'})).status,200);
assert.equal((await save('inactive-assignment','patient',{name:'Atribuição inativa',therapist:'inactive-profile'})).status,400);
r=await save('imported-incomplete','patient',{...importedData,therapist:'actual-therapist'},2);assert.equal(r.status,200);importedData=r.data.record.data;
staff();r=await call(dataAPI,'GET','/api/data');assert.ok(r.data.records.some(x=>x.id==='imported-incomplete'));
assert.equal((await save('imported-incomplete','patient',{...importedData,therapist:''},3)).status,403);
realOwner();
console.log('Incomplete intake passed: unknown age and therapist remain blank, later edits and assignment work, invalid values are rejected, and staff and family access stay scoped.');

// Child/family intake, multiple guardians, siblings and per-child consent.
realOwner();
const contacts=[{id:'mother',name:'Responsável A',relationship:'Mãe',email:'  MOM@example.invalid ',phone:'210000000',shareAuthorized:'Sim',consentNote:'Autorização registada'},{id:'father',name:'Responsável B',relationship:'Pai',email:'dad@example.invalid',phone:'',shareAuthorized:'Sim',consentNote:'Autorização registada'}];
let childData={name:'Criança do cadastro',birthDate:'2019-02-28',therapist:'actual-therapist',status:'Ativo',guardians:contacts,familyName:'Família do cadastro'};
r=await save('intake-child','patient',childData);assert.equal(r.status,200);assert.equal(r.data.record.data.guardians[0].email,'mom@example.invalid');assert.equal(r.data.record.data.familyId,'intake-child');assert.ok(r.data.record.data.guardians[0].consentAt);assert.equal(r.data.record.data.guardians[0].consentBy,'real-clinic');childData=r.data.record.data;
assert.equal((await save('invalid-dob','patient',{...childData,name:'Data inválida',birthDate:'2019-02-29'})).status,400);
assert.equal((await save('duplicate','patient',childData)).status,400);
assert.equal((await save('duplicate-mail','patient',{...childData,name:'Outro nome',guardians:[...contacts,{...contacts[1],id:'duplicate',email:'MOM@example.invalid'}]})).status,400);
assert.equal((await save('bad-family','patient',{...childData,name:'Outra criança',familyId:'nonexistent'})).status,400);
const shareFor=(id,recipient,child='intake-child')=>call(pro,'POST','/api/family',{patientId:child,action:'publish',id,recipient,type:'Orientações para casa',title:'Orientação revista',body:'CONTEUDO_PARA_'+recipient,confirmed:true});
for(const email of ['mom@example.invalid','dad@example.invalid'])assert.equal((await call(pro,'POST','/api/family',{patientId:'intake-child',action:'grant',email,enabled:true})).status,200);
assert.equal((await shareFor('for-mom','mom@example.invalid')).status,200);assert.equal((await shareFor('for-dad','dad@example.invalid')).status,200);assert.equal((await shareFor('for-stranger','stranger@example.invalid')).status,400);
assert.equal((await save('intake-sibling','patient',{name:'Irmão do cadastro',birthDate:'2021-05-10',therapist:'owner-profile',status:'Ativo',familyId:'intake-child',guardians:contacts.map(g=>({...g,shareAuthorized:'Não'}))})).status,200);
assert.equal((await call(pro,'POST','/api/family',{patientId:'intake-sibling',action:'grant',email:'mom@example.invalid',enabled:true})).status,400);
const mom=()=>globalThis.familyTest.user={userId:'mom',email:'mom@example.invalid',displayName:'Mãe'},dad=()=>globalThis.familyTest.user={userId:'dad',email:'dad@example.invalid',displayName:'Pai'};
mom();r=await call(parent,'GET','/api/parents');assert.equal(r.data.children.length,1);assert.equal(r.data.view.publications.length,1);assert.ok(r.data.view.publications[0].body.includes('mom@'));assert.equal(JSON.stringify(r.data).includes('dad@'),false);assert.equal(JSON.stringify(r.data).includes('2019-02-28'),false);
dad();r=await call(parent,'GET','/api/parents');assert.equal(r.data.children.length,1);assert.ok(r.data.view.publications[0].body.includes('dad@'));
realOwner();r=await call(dataAPI,'GET','/api/data');let sibling=r.data.records.find(x=>x.id==='intake-sibling');sibling.data.guardians[0].shareAuthorized='Sim';assert.equal((await save(sibling.id,'patient',sibling.data,1)).status,200);assert.equal((await call(pro,'POST','/api/family',{patientId:sibling.id,action:'grant',email:'mom@example.invalid',enabled:true})).status,200);
mom();r=await call(parent,'GET','/api/parents');assert.equal(r.data.children.length,2);
staff();r=await call(dataAPI,'GET','/api/data');assert.ok(r.data.records.some(x=>x.id==='intake-child'));assert.equal(r.data.records.some(x=>x.id==='intake-sibling'),false);assert.equal((await save('guess-family','patient',{name:'Sem acesso',age:6,therapist:'actual-therapist',familyId:'not-assigned',status:'Ativo'})).status,400);
realOwner();const revoked={...childData,guardians:childData.guardians.map(g=>g.id==='father'?{...g,shareAuthorized:'Não'}:g)};
assert.equal((await save('intake-child','patient',revoked,0)).status,409);assert.equal(sqlite.prepare('SELECT enabled FROM family_access WHERE patient_id=? AND email=?').get('intake-child','dad@example.invalid').enabled,1);
assert.equal((await save('intake-child','patient',revoked,1)).status,200);assert.equal(sqlite.prepare('SELECT enabled FROM family_access WHERE patient_id=? AND email=?').get('intake-child','dad@example.invalid').enabled,0);
dad();assert.equal((await call(parent,'GET','/api/parents')).data.children.length,0);mom();assert.equal((await call(parent,'GET','/api/parents')).data.children.length,2);
realOwner();assert.equal((await save('intake-child','patient',childData,2)).status,200);dad();assert.equal((await call(parent,'GET','/api/parents')).data.children.length,0); // restoring consent does not silently restore access
realOwner();assert.equal((await call(pro,'POST','/api/family',{patientId:'intake-child',action:'grant',email:'dad@example.invalid',enabled:true})).status,200);
assert.equal((await save('intake-child','patient',{...childData,status:'Arquivado'},3)).status,200);dad();assert.equal((await call(parent,'GET','/api/parents')).data.children.length,0);mom();assert.equal((await call(parent,'GET','/api/parents')).data.children.length,1);
console.log('Child/family registry passed: birth dates, duplicate checks, durable contact links, multiple guardians, siblings, per-child consent, recipient isolation, therapist scope, stale-write rollback and access revocation.');
