import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const sqlite=new DatabaseSync(':memory:');sqlite.exec('CREATE TABLE records(id TEXT PRIMARY KEY,clinic TEXT,kind TEXT,data TEXT,author TEXT,version INTEGER,updated TEXT); CREATE TABLE audit(id TEXT PRIMARY KEY,clinic TEXT,actor TEXT,action TEXT,record_id TEXT,created TEXT);CREATE TABLE integration_connections(clinic TEXT,user_id TEXT,provider TEXT,payload TEXT,version INTEGER,updated TEXT,PRIMARY KEY(clinic,user_id,provider));');
const db={
 prepare(sql){return {bind(...args){return {
 async first(){return sqlite.prepare(sql).get(...args)||null},
 async all(){return {results:sqlite.prepare(sql).all(...args)}},
 async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}}}
 }}}},
 async batch(queries){sqlite.exec('BEGIN');try{const out=[];for(const q of queries)out.push(await q.run());sqlite.exec('COMMIT');return out}catch(e){sqlite.exec('ROLLBACK');throw e}}
};
globalThis.integrationTest={db,identity:{tenant:'c',role:'therapist',therapist:'t',user:{userId:'u'}},env:{GOOGLE_CLIENT_ID:'test-client',GOOGLE_CLIENT_SECRET:'FAKE_TEST_SECRET',RESEND_WEBHOOK_SECRET:'whsec_'+Buffer.from('fake-test-signing-key').toString('base64')},jar:new Map()};
const mocks={
 'cloudflare:workers':url('export const env=globalThis.integrationTest.env;'),
 'next/headers':url('export const cookies=async()=>({get:k=>globalThis.integrationTest.jar.has(k)?{value:globalThis.integrationTest.jar.get(k)}:null,set:(k,v)=>globalThis.integrationTest.jar.set(k,v),delete:k=>globalThis.integrationTest.jar.delete(k)});'),
 '@/lib/server':url("export const db=()=>globalThis.integrationTest.db;export const identity=async()=>{if(!globalThis.integrationTest.identity)throw new AppError('Auth',401);return globalThis.integrationTest.identity};export class AppError extends Error{constructor(m,status=400){super(m);this.status=status}};export const checkOrigin=r=>{if(r.headers.get('origin')&&r.headers.get('origin')!==new URL(r.url).origin)throw new AppError('Origin',403)};export const failure=e=>Response.json({error:e.message},{status:e.status||503});export async function allRecords(a){return (await db().prepare('SELECT * FROM records WHERE clinic=?').bind(a.tenant).all()).results.map(r=>({...r,id:r.id.slice(a.tenant.length+1),data:JSON.parse(r.data)}))};"),
 './supabase-http':url("export const serviceConfig=()=>({SUPABASE_SECRET_KEY:'FAKE_DB_TEST_KEY'});"),
 'zod':pathToFileURL(require.resolve('zod')).href
};mocks['./server']=mocks['@/lib/server'];
const modules=new Map();function module(file){file=path.resolve(file);if(modules.has(file))return modules.get(file);let code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;code=code.replace(/from (['"])([^'"]+)\1/g,(_,q,s)=>'from '+JSON.stringify(mocks[s]||module(s.startsWith('@/')?s.slice(2)+'.ts':path.resolve(path.dirname(file),s+'.ts'))));const out=url(code);modules.set(file,out);return out;}
const calendar=await import(module('lib/calendar.ts')),server=await import(module('lib/integrations-server.ts')),email=await import(module('lib/email-events.ts')),api=await import(module('app/api/integrations/route.ts')),callback=await import(module('app/api/integrations/google/callback/route.ts')),sync=await import(module('app/api/integrations/calendar/route.ts')),webhook=await import(module('app/api/integrations/email/webhook/route.ts'));
const a=globalThis.integrationTest.identity,put=(id,kind,data,clinic='c')=>sqlite.prepare('INSERT OR REPLACE INTO records VALUES(?,?,?,?,?,1,?)').run(clinic+':'+id,clinic,kind,JSON.stringify(data),'u','2026-10-07'),get=id=>JSON.parse(sqlite.prepare('SELECT data FROM records WHERE id=?').get('c:'+id).data);
put('p','patient',{name:'PRIVATE_CHILD',therapist:'t'});put('p2','patient',{name:'PRIVATE_OTHER_CHILD',therapist:'other'});
put('ap','appointment',{patientId:'p',therapist:'t',date:'2026-10-27',time:'16:00',duration:45,status:'Esperado',context:'Online',internalNote:'PRIVATE_NOTES'});put('ap-other','appointment',{patientId:'p2',therapist:'other',date:'2026-10-27',time:'16:00',duration:45,status:'Esperado'});put('ap-cross','appointment',{patientId:'p',therapist:'t',date:'2026-10-27',time:'16:00',duration:45},'other-clinic');
const request=(p,body)=>new Request('https://clinic.invalid'+p,body?{method:'POST',headers:{'content-type':'application/json',origin:'https://clinic.invalid'},body:JSON.stringify(body)}:undefined);
assert.equal(calendar.videoUrl('javascript:alert(1)'), '');assert.equal(calendar.videoUrl('https://meet.google.com.evil.invalid/x'),'');assert.equal(calendar.videoUrl('https://user@meet.google.com/x'),'');assert.equal(calendar.videoUrl('https://meet.google.com/abc-defg-hij'),'https://meet.google.com/abc-defg-hij');
assert.deepEqual(calendar.appointmentTimes({date:'2026-10-27',time:'23:30',duration:30}),{start:'2026-10-27T23:30:00',end:'2026-10-28T00:00:00'});
let r=await api.GET(request('/api/integrations?ics=1'));assert.equal(r.status,200);const ics=await r.text();assert(ics.includes('TZID:Europe/Lisbon'));assert(ics.includes('20261027T160000'));assert(!ics.includes('PRIVATE_CHILD'));assert(!ics.includes('PRIVATE_NOTES'));assert(!ics.includes('ap-other'));assert(!ics.includes('ap-cross'));for(const line of ics.split('\r\n'))assert(Buffer.byteLength(line)<=75);
const sealed=await server.seal({secret:'FAKE_TOKEN'},'c:u');assert(!sealed.includes('FAKE_TOKEN'));assert.deepEqual(await server.unseal(sealed,'c:u'),{secret:'FAKE_TOKEN'});await assert.rejects(()=>server.unseal(sealed,'other:u'));
let calls=[];globalThis.fetch=async(input,opts={})=>{calls.push({url:String(input),opts});if(String(input).includes('oauth2.googleapis.com/token'))return Response.json({access_token:'FAKE_ACCESS',refresh_token:'FAKE_REFRESH',expires_in:3600,scope:'https://www.googleapis.com/auth/calendar.events.owned'});if(opts.method==='POST'&&String(input).includes('/events?'))return Response.json({hangoutLink:'https://meet.google.com/abc-defg-hij'});if(opts.method==='DELETE')return new Response(null,{status:204});return new Response(null,{status:404})};
r=await api.POST(request('/api/integrations',{action:'connectGoogle'}));assert.equal(r.status,200);const authUrl=new URL((await r.json()).url);assert.equal(authUrl.origin,'https://accounts.google.com');assert.equal(authUrl.searchParams.get('code_challenge_method'),'S256');assert.equal(authUrl.searchParams.get('scope'),'https://www.googleapis.com/auth/calendar.events.owned');assert(!authUrl.href.includes('FAKE_TEST_SECRET'));
const state=authUrl.searchParams.get('state');r=await callback.GET(request('/api/integrations/google/callback?state='+state+'&code=fake-code'));assert.equal(r.status,303);assert(r.headers.get('location').includes('google=connected'));assert(!sqlite.prepare('SELECT payload FROM integration_connections').get().payload.includes('FAKE_REFRESH'));assert.equal((await server.googleConnection(a)).refreshToken,'FAKE_REFRESH');
calls=[];r=await sync.POST(request('/api/integrations/calendar',{id:'ap-other',version:1,meet:false}));assert.equal(r.status,403);assert.equal(calls.length,0);r=await sync.POST(request('/api/integrations/calendar',{id:'ap',version:0,meet:true}));assert.equal(r.status,409);assert.equal(calls.length,0);
r=await sync.POST(request('/api/integrations/calendar',{id:'ap',version:1,meet:true}));assert.equal(r.status,200);assert.equal(get('ap').videoUrl,'https://meet.google.com/abc-defg-hij');const sent=JSON.parse(calls.find(x=>x.opts.method==='POST').opts.body);assert.equal(sent.start.timeZone,'Europe/Lisbon');assert(sent.conferenceData);assert(!JSON.stringify(sent).includes('PRIVATE_CHILD'));assert(!JSON.stringify(sent).includes('PRIVATE_NOTES'));assert(!sent.attendees);assert.equal(get('ap').calendarStatus,'Sincronizado');
const {validateWorkflow}=await import(module('lib/workflows.ts'));
const rows=[{id:'p',kind:'patient',data:{therapist:'t'},version:1},{id:'t',kind:'team',data:{status:'Ativo'},version:1}];
const booking={id:'manual',kind:'appointment',version:0,data:{name:'Sessão',patientId:'p',therapist:'t',date:'2026-10-27',time:'16:00',duration:45,context:'Online',status:'Esperado',videoUrl:'https://meet.google.com/abc-defg-hij',calendarStatus:'Sincronizado'}};
validateWorkflow(booking,undefined,rows,a);assert.equal(booking.data.calendarStatus,'');assert.equal(booking.data.videoStatus,'Ligação guardada');
assert.throws(()=>validateWorkflow({...booking,data:{...booking.data,videoUrl:'https://evil.invalid/phishing'}},undefined,rows,a),/HTTPS/);
const other=await server.googleConnection({...a,user:{userId:'other-user'}});assert.equal(other,null);
// Wrong or replayed OAuth state never contacts Google.
const before=calls.length;r=await callback.GET(request('/api/integrations/google/callback?state='+state+'&code=fake-code'));assert(r.headers.get('location').includes('google=failed'));assert.equal(calls.length,before);
put('delivery','delivery',{patientId:'p',recipient:'authorized@example.invalid',providerId:'provider-test',status:'Aceite pelo serviço',body:'PRIVATE_SUMMARY'});
const secret=globalThis.integrationTest.env.RESEND_WEBHOOK_SECRET,now=Date.now(),timestamp=String(Math.floor(now/1000));
async function signed(type,id='message-test',created=new Date(now).toISOString()){const body=JSON.stringify({type,created_at:created,data:{email_id:'provider-test'}}),key=await crypto.subtle.importKey('raw',Uint8Array.from(Buffer.from(secret.slice(6),'base64')),{name:'HMAC',hash:'SHA-256'},false,['sign']),signature=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(id+'.'+timestamp+'.'+body))).toString('base64');return new Request('https://clinic.invalid/api/integrations/email/webhook',{method:'POST',headers:{'svix-id':id,'svix-timestamp':timestamp,'svix-signature':'v1,'+signature},body});}
r=await webhook.POST(await signed('email.delivered'));assert.equal(r.status,200);assert.equal(get('delivery').status,'Entregue');const count=sqlite.prepare("SELECT count(*) n FROM audit WHERE action='email.delivered'").get().n;assert.equal(count,1);r=await webhook.POST(await signed('email.delivered'));assert.equal(r.status,200);assert.equal(sqlite.prepare("SELECT count(*) n FROM audit WHERE action='email.delivered'").get().n,1);assert(!get('email-event-message-test').body.includes('PRIVATE_SUMMARY'));
r=await webhook.POST(await signed('email.sent','later-sent',new Date(now+1000).toISOString()));assert.equal(get('delivery').status,'Entregue');
await assert.rejects(async()=>email.verifyEmailWebhook('{"tampered":1}',(await signed('email.delivered')).headers,secret));await assert.rejects(()=>email.verifyEmailWebhook('{}',new Headers({'svix-id':'old','svix-timestamp':'1','svix-signature':'v1,fake'}),secret));
globalThis.integrationTest.identity=null;r=await api.GET(request('/api/integrations?ics=1'));assert.equal(r.status,401);
console.log('Integrations passed: scoped private ICS, Lisbon timezone, encrypted/account-bound OAuth tokens, PKCE/state and replay protection, Calendar/Meet with clinical-data exclusion, authorization/version guards and verified/deduplicated delivery webhooks.');
