import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';

const compile=file=>ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const url=source=>'data:text/javascript;base64,'+Buffer.from(source).toString('base64');
const careUrl=url(compile('lib/care.ts'));
const {attendanceIssues,attendanceNoticeChanges,monthlyReferenceHours,visitTransitionData}=await import(careUrl);
const {paymentDate,isOverdueIncome,normalizeInvoicePayment}=await import(url(compile('lib/finance.ts')));
const rec=(id,kind,data,version=1)=>({id,kind,data,version});
const now={date:'2026-10-07',time:'10:00'},stamp='2026-10-07T09:00:00.000Z';
const team=rec('t','team',{name:'Terapeuta de teste',status:'Ativo',startTime:'09:00',workDays:'1,2,3,4,5'});
const entrance=time=>rec('entry','attendance',{therapist:'t',date:now.date,type:'Entrada',time});

assert.equal(monthlyReferenceHours({}),null);
assert.equal(monthlyReferenceHours({hours:'',monthlyHours:''}),null);
assert.equal(monthlyReferenceHours({hours:35,monthlyHours:0}),0);
assert.equal(monthlyReferenceHours({hours:0}),0);
assert.equal(monthlyReferenceHours({hours:20}),86.6);
assert.equal(monthlyReferenceHours({hours:-1}),null);
assert.equal(attendanceIssues([team],now).length,1);
for(const status of ['Inativo','Arquivado','Ausente'])assert.equal(attendanceIssues([{...team,data:{...team.data,status}}],now).length,0);
assert.equal(attendanceIssues([{...team,data:{...team.data,archived:true}}],now).length,0);
const leave=rec('leave','leave',{therapist:'t',date:now.date,endDate:now.date,status:'Aprovado'});
assert.equal(attendanceIssues([team,leave],now).length,0);

const first=attendanceNoticeChanges([team],now,stamp)[0];
const persisted={...first,version:1,data:{...first.data,readBy:['director']}};
assert.equal(attendanceNoticeChanges([team,persisted],now,stamp).length,0);
const late=attendanceNoticeChanges([team,persisted,entrance('09:25')],now,stamp)[0];
assert.match(late.data.name,/entrada com atraso/);
assert.doesNotMatch(late.data.body,/Sem entrada registada/);
assert.deepEqual(late.data.readBy,['director']);
assert.equal(late.data.history[0].body,persisted.data.body);
assert.equal(late.data.createdAt,persisted.data.createdAt);
const resolved=attendanceNoticeChanges([team,persisted,entrance('09:05')],now,stamp)[0];
assert.equal(resolved.data.status,'Resolvido');
assert.match(resolved.data.body,/09:05/);
assert.equal(attendanceNoticeChanges([team,resolved,entrance('09:05')],now,stamp).length,0);
assert.equal(attendanceNoticeChanges([team,persisted,leave],now,stamp)[0].data.status,'Resolvido');
const tomorrow={date:'2026-10-08',time:'08:00'};
const historical=attendanceNoticeChanges([team,persisted,entrance('09:25')],tomorrow,stamp)[0];
assert.match(historical.data.body,/Entrada registada às 09:25/);
assert.doesNotMatch(historical.data.body,/Sem entrada registada/);
assert.equal(attendanceNoticeChanges([team,historical,entrance('09:25')],tomorrow,stamp).length,0);

const invoice=rec('i','invoice',{name:'Exemplo',type:'Receita',status:'Por pagar',date:'2026-10-01',dueDate:'2026-10-31',amount:50});
assert.equal(isOverdueIncome(invoice,now.date),false);
assert.equal(isOverdueIncome({...invoice,data:{...invoice.data,dueDate:'2026-10-06'}},now.date),true);
assert.equal(isOverdueIncome({...invoice,data:{...invoice.data,type:'Custo',dueDate:'2026-10-06'}},now.date),false);
assert.equal(isOverdueIncome({...invoice,data:{...invoice.data,dueDate:now.date}},now.date),false);
const legacy={...invoice,data:{...invoice.data,status:'Pago'}};
assert.equal(paymentDate(legacy),'');
const edited=structuredClone(legacy);normalizeInvoicePayment(edited,legacy,now.date);
assert.equal(paymentDate(edited),'');
const paid={...invoice,data:{...invoice.data,status:'Pago'}};normalizeInvoicePayment(paid,invoice,now.date);
assert.equal(paymentDate(paid),now.date);
const previousMonth=rec('september','invoice',{type:'Receita',status:'Pago',date:'2026-09-01',paymentDate:'2026-10-02',amount:20});
assert.equal(paymentDate(previousMonth).startsWith('2026-10'),true);
assert.equal(paymentDate(previousMonth).startsWith('2026-09'),false);
const bad={...paid,data:{...paid.data,paymentDate:'2026-02-30'}};
assert.throws(()=>normalizeInvoicePayment(bad,paid,now.date),/inválida/);
assert.throws(()=>normalizeInvoicePayment({...paid,data:{...paid.data,paymentDate:'2026-10-08'}},paid,now.date),/futura/);
const reversed={...paid,data:{...paid.data,status:'Por pagar'}};normalizeInvoicePayment(reversed,paid,now.date);
assert.equal(reversed.data.paymentDate,'');
assert.equal(paymentDate(reversed),'');

const departed=visitTransitionData({status:'A caminho'},{status:'Previsto'},stamp);
assert.equal(departed.departedAt,stamp);assert.equal(departed.checkout,undefined);
const arrived=visitTransitionData({...departed,status:'Na escola'},departed,'2026-10-07T10:00:00Z');
const completed=visitTransitionData({...arrived,status:'Concluído'},arrived,'2026-10-07T11:00:00Z');
const approved=visitTransitionData({...completed,status:'Aprovado',checkout:'forged'},completed,'2026-10-08T11:00:00Z');
const reimbursed=visitTransitionData({...approved,status:'Pago'},approved,'2026-10-09T11:00:00Z');
assert.equal(reimbursed.checkin,arrived.checkin);assert.equal(reimbursed.checkout,completed.checkout);
assert.equal(reimbursed.approvedAt,'2026-10-08T11:00:00Z');assert.equal(reimbursed.paidAt,'2026-10-09T11:00:00Z');

// Exercise actual persistence through runClinic, including idempotency and tenant isolation.
const RealDate=Date;
globalThis.Date=class extends RealDate {constructor(...args){super(...(args.length?args:[stamp]));}static now(){return RealDate.parse(stamp);}};
const sqlite=new DatabaseSync(':memory:');
sqlite.exec('CREATE TABLE records(id TEXT PRIMARY KEY,clinic TEXT,kind TEXT,data TEXT,author TEXT,version INTEGER,updated TEXT)');
const database={prepare(sql){return{bind(...args){return{async run(){return{meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}}},async all(){return{results:sqlite.prepare(sql).all(...args)}}}}}},async batch(statements){const result=[];sqlite.exec('BEGIN');try{for(const statement of statements)result.push(await statement.run());sqlite.exec('COMMIT');return result}catch(error){sqlite.exec('ROLLBACK');throw error}}};
globalThis.operationsTest={db:database};
const server=url(`export const db=()=>globalThis.operationsTest.db;export class AppError extends Error{};export async function allRecords(a){const rows=await db().prepare('SELECT * FROM records WHERE clinic=?').bind(a.tenant).all();return rows.results.map(r=>({...r,id:r.id.slice(a.tenant.length+1),data:JSON.parse(r.data)}))}`);
const mailServer=url('export const mailReady=async()=>false;export async function prepareMail(){throw Error("Email not configured in operations tests")}');
const careServer=url(compile('lib/care-server.ts').replace("'cloudflare:workers'",JSON.stringify(url('export const env={}'))).replace("'./server'",JSON.stringify(server)).replaceAll("'./mail-server'",JSON.stringify(mailServer)).replace("'./care'",JSON.stringify(careUrl)));
const {runClinic}=await import(careServer);
const put=(r,clinic='c')=>sqlite.prepare('INSERT OR REPLACE INTO records VALUES(?,?,?,?,?,?,?)').run(clinic+':'+r.id,clinic,r.kind,JSON.stringify(r.data),'u',r.version,stamp);
const get=id=>{const r=sqlite.prepare('SELECT * FROM records WHERE id=?').get(id);return {...r,data:JSON.parse(r.data)}};
put(team);put(persisted);put(persisted,'other');put(entrance('09:25'));
await runClinic({tenant:'c',user:{userId:'u'}});
const saved=get('c:'+persisted.id);assert.equal(saved.version,2);assert.match(saved.data.body,/Entrada 09:25/);assert.deepEqual(saved.data.readBy,['director']);
await runClinic({tenant:'c',user:{userId:'u'}});assert.equal(get('c:'+persisted.id).version,2);
assert.equal(get('other:'+persisted.id).version,1);
put(leave);await runClinic({tenant:'c',user:{userId:'u'}});assert.equal(get('c:'+persisted.id).data.status,'Resolvido');
globalThis.Date=RealDate;
console.log('Operations and finance: attendance reconciliation, preserved history, missing hours, visit timestamps, due dates and cash dates passed.');
