import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const compile=file=>ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const catalog=JSON.parse(fs.readFileSync('lib/query-catalog.json','utf8'));
let requests=[];
const http=url('export const databaseRequest=async body=>{globalThis.dbRequests.push(body);return body.operations.map(()=>({results:[],meta:{changes:1}}))}');
globalThis.dbRequests=requests;
const adapter=await import(url(compile('lib/supabase-database.ts').replace("import catalog from './query-catalog.json';",'const catalog='+JSON.stringify(catalog)+';').replace("'./supabase-http'",JSON.stringify(http))));
const d=adapter.database();
await d.batch([d.prepare('SELECT * FROM memberships WHERE email=?').bind("value'); DROP TABLE records; --"),d.prepare('SELECT * FROM memberships WHERE email=?').bind('other@example.invalid')]);
assert.equal(requests.length,1);assert.equal(requests[0].operations.length,2);assert.ok(!JSON.stringify(requests[0]).includes('query_text'));assert.equal(requests[0].operations[0].args[0],"value'); DROP TABLE records; --");
await assert.rejects(()=>d.prepare('SELECT * FROM auth.users').all(),/not registered/);
await assert.rejects(()=>d.prepare('SELECT * FROM memberships WHERE email=?').all(),/parameters/);
assert.equal(requests.length,1);

const jar=new Map(),headers=url('export const cookies=async()=>({get:n=>globalThis.authJar.has(n)?{value:globalThis.authJar.get(n)}:undefined,set:(n,v,o)=>{globalThis.authJar.set(n,v);globalThis.cookieOptions.push(o)},delete:n=>globalThis.authJar.delete(n)})');
globalThis.authJar=jar;globalThis.cookieOptions=[];
globalThis.authState={email:'owner@example.invalid',id:'00000000-0000-4000-8000-000000000001',session:true,member:null,grants:[],patient:null,fetches:[]};
const authDb=url(`export const database=()=>({prepare:sql=>({bind:(...args)=>({first:async()=>{const s=globalThis.authState;if(sql.includes('auth.sessions'))return s.session?{id:args[0]}:null;if(sql.includes('memberships'))return s.member;if(sql.includes("kind='team'"))return {data:JSON.stringify({status:s.profileStatus||'Ativo'})};if(sql.includes("kind='patient'"))return s.patient?{data:JSON.stringify(s.patient)}:null;return null;},all:async()=>({results:globalThis.authState.grants})})})});`);
const authHttp=url(`export const publicConfig=()=>({CLINIC_OWNER_EMAIL:'owner@example.invalid'});export const authRequest=async(path,body,token)=>{const s=globalThis.authState;s.fetches.push({path,body,token});if(path==='user'){if(token===s.invalidToken)return Response.json({},{status:401});return Response.json({id:s.id,email:s.email,email_confirmed_at:'2026-10-07',user_metadata:{name:'Display only',role:'director'}});}if(path.startsWith('token?'))return Response.json({access_token:s.token,refresh_token:'rotated-refresh',expires_in:3600});if(path.startsWith('logout')){s.session=false;return Response.json({ok:true});}throw Error('Unexpected request');};`);
const family=url("export const eligiblePatient=(p,email)=>!!p&&p.data.shareAuthorized==='Sim'&&p.data.guardianEmail===email&&p.data.status!=='Arquivado';");
const auth=await import(url(compile('lib/auth.ts').replace("'next/headers'",JSON.stringify(headers)).replace("'./supabase-http'",JSON.stringify(authHttp)).replace("'./supabase-database'",JSON.stringify(authDb)).replace("'./family'",JSON.stringify(family))));
const token='header.'+Buffer.from(JSON.stringify({session_id:'00000000-0000-4000-8000-000000000002'})).toString('base64url')+'.signature';globalThis.authState.token=token;
assert.equal(await auth.authorizedEmail('OWNER@example.invalid'),true);
assert.equal(await auth.authorizedEmail('unknown@example.invalid'),false);
globalThis.authState.member={enabled:1,clinic:'c',therapist:'t'};assert.equal(await auth.authorizedEmail('staff@example.invalid'),true);
globalThis.authState.profileStatus='Inativo';assert.equal(await auth.authorizedEmail('staff@example.invalid'),false);
globalThis.authState.profileStatus='Ativo';globalThis.authState.member.enabled=0;assert.equal(await auth.authorizedEmail('staff@example.invalid'),false);
globalThis.authState.member=null;globalThis.authState.grants=[{clinic:'c',patient_id:'p'}];globalThis.authState.patient={guardianEmail:'parent@example.invalid',shareAuthorized:'Sim',status:'Ativo'};
assert.equal(await auth.authorizedEmail('parent@example.invalid'),true);globalThis.authState.patient.shareAuthorized='Não';assert.equal(await auth.authorizedEmail('parent@example.invalid'),false);
await auth.setSession({access_token:token,refresh_token:'refresh',expires_in:7200});assert.equal(globalThis.cookieOptions[0].httpOnly,true);assert.equal(globalThis.cookieOptions[0].secure,true);assert.equal(globalThis.cookieOptions[0].sameSite,'lax');assert.equal(globalThis.cookieOptions[0].maxAge,3600);
assert.equal((await auth.currentUser()).userId,globalThis.authState.id);
assert.equal((await auth.currentUser()).role,undefined); // User-editable metadata never grants a role.
globalThis.authState.session=false;assert.equal(await auth.currentUser(),null);
globalThis.authState.session=true;globalThis.authState.invalidToken=token+'expired';jar.set('linguar-access',token+'expired');assert.equal((await auth.currentUser()).userId,globalThis.authState.id);assert.equal(jar.get('linguar-refresh'),'rotated-refresh');
await auth.signOut();assert.equal(jar.size,0);assert.equal(globalThis.authState.session,false);
assert.equal(auth.returnPath('https://attacker.invalid'),'/');assert.equal(auth.returnPath('//attacker.invalid'),'/');assert.equal(auth.returnPath('/pais'),'/pais');
console.log('Supabase integration passed: registered operations, one-request batches, injection-resistant parameters, email authorization, consent, secure cookies, online user verification, active sessions, refresh, logout and safe redirects.');
