import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const compile=file=>ts.transpileModule(fs.readFileSync(new URL('../lib/'+file+'.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const url=body=>'data:text/javascript;base64,'+Buffer.from(body).toString('base64');
const accessUrl=url(compile('access'));
const {visible}=await import(accessUrl);
const {validateWorkflow}=await import(url(compile('workflows').replace("'./access'",JSON.stringify(accessUrl))));
const {workedMinutes,availableSlots,flags,sessionAccuracy}=await import(url(compile('clinical')));
const a={role:'therapist',therapist:'t1',user:{userId:'u1'}},director={role:'director',therapist:'t3',user:{userId:'owner'}};
const rec=(id,kind,data,author='u1')=>({id,kind,data,author,version:1});
const patient=rec('p1','patient',{therapist:'t1'}),t1=rec('t1','team',{name:'Ana'}),t2=rec('t2','team',{name:'Joana'}),t3=rec('t3','team',{name:'Diretor'});
const channel=rec('private','channel',{private:'Sim',members:['t1','t2']});
const privateMessage=rec('m','message',{channel:'private',body:'hello'});
const dm=rec('dm','message',{dm:true,members:['t1','t2'],body:'hello',attachment:'f'});
const f=rec('f','file',{visibility:'Pessoal'},'u2');const rows=[patient,t1,t2,t3,channel,privateMessage,dm,f,rec('school','school',{name:'Escola'})];
assert.equal(visible(privateMessage,a,rows),true);
assert.equal(visible(privateMessage,{...a,therapist:'t3'},rows),false);
assert.equal(visible(dm,director,rows),false);
assert.equal(visible(f,a,rows),true);
assert.equal(visible(f,director,rows),false);
assert.equal(visible(rec('w','wellbeing',{},'u2'),director,rows),false);
assert.throws(()=>validateWorkflow(rec('s','session',{}),undefined,rows,a),/paciente/);
assert.throws(()=>validateWorkflow(rec('d','document',{patientId:'p1'}),undefined,rows,a),/obrigatórios/);
assert.throws(()=>validateWorkflow(rec('d','document',{patientId:'p1'}),rec('d','document',{}),rows,director),/imutáveis/);
assert.throws(()=>validateWorkflow(rec('v','visit',{km:10,status:'Pago',school:'school'}),rec('v','visit',{status:'Concluído'}),rows,director),/aprovada/);
assert.throws(()=>validateWorkflow(rec('w','wellbeing',{load:6,satisfaction:3}),undefined,rows,a),/escala/);
assert.throws(()=>validateWorkflow(rec('x','message',{channel:'private',body:'x'}),undefined,rows,{...a,therapist:'t3'}),/Sem acesso/);
const message=rec('new','message',{channel:'geral',body:'x',authorName:'FORGED',date:'2000-01-01'});
validateWorkflow(message,undefined,rows,a);assert.equal(message.data.authorName,'Ana');assert.notEqual(message.data.date,'2000-01-01');
const reaction=rec('m','message',{...privateMessage.data,body:'tampered',react:'👍'});validateWorkflow(reaction,privateMessage,rows,a);assert.equal(reaction.data.body,'hello');assert.deepEqual(reaction.data.reactions['👍'],['u1']);
const e=(id,time,type)=>rec(id,'attendance',{therapist:'t1',date:'2026-09-18',time,type});const entries=[e('a','09:00','Entrada'),e('b','12:00','Pausa'),e('c','13:00','Retoma'),e('d','17:00','Saída')];
assert.equal(workedMinutes(entries,'t1','2026-09'),420);
assert.equal(workedMinutes(entries.slice(0,3),'t1','2026-09'),180);
assert.throws(()=>validateWorkflow(e('e','18:00','Saída'),undefined,entries,a),/Sequência/);
assert.throws(()=>validateWorkflow(rec('l2','leave',{therapist:'t1',date:'2026-09-19',endDate:'2026-09-23',status:'Aprovado'}),undefined,[rec('l1','leave',{therapist:'t1',date:'2026-09-20',endDate:'2026-09-22',status:'Aprovado'})],director),/ausência aprovada/);
const appointment=rec('ap','appointment',{date:'2026-09-18',time:'09:00',duration:45,therapist:'t1',patientId:'p1',room:'r1',status:'Esperado'});
const slots=availableSlots([appointment],{date:'2026-09-18',duration:45,therapist:'t1',patientId:'p1',room:'r1'});assert(!slots.includes('08:30'));assert(!slots.includes('09:30'));assert(slots.includes('09:45'));
assert.equal(sessionAccuracy(rec('s','session',{correct:8,help:1,error:1})),80);
assert.equal(flags([patient,rec('s','session',{patientId:'p1',date:'2026-09-01',correct:1,help:0,error:0})],'2026-09-18')[0].type,'Inatividade');
// Worlds preserve missing progress and use server-authored provenance.
const worlds=rec('p1','patient',{therapist:'t1',worldsProgress:[100,50,null,null,null,null,null,null],currentWorld:1,worldsUpdatedBy:'forged'});
validateWorkflow(worlds,patient,rows,a);assert.equal(worlds.data.worldsUpdatedBy,'u1');assert.equal(worlds.data.worldsProgress[2],null);
const unchanged=rec('p1','patient',{...worlds.data,strategies:'Contextos funcionais',worldsUpdatedBy:'forged'});
validateWorkflow(unchanged,worlds,rows,a);assert.equal(unchanged.data.worldsUpdatedBy,'u1');
assert.throws(()=>validateWorkflow(rec('p1','patient',{worldsProgress:[101,0,0,0,0,0,0,0]}),patient,rows,a),/oito valores/);
assert.throws(()=>validateWorkflow(rec('p1','patient',{worldsProgress:[50]}),patient,rows,a),/oito valores/);
assert.throws(()=>validateWorkflow(rec('p1','patient',{currentWorld:8}),patient,rows,a),/Mundo inválido/);
console.log('32 workflow, privacy, worlds and clinical calculation checks passed');

// Structured plans, TPC and shared operational records.
assert.throws(()=>validateWorkflow(rec('plan','plan',{patientId:'p1',status:'Ativo'}),undefined,rows,a),/direção/);
assert.throws(()=>validateWorkflow(rec('plan','plan',{patientId:'p1',goals:[{id:'g',name:'Som alvo',progress:101,status:'Em progresso'}]}),undefined,rows,director),/objetivos/);
assert.throws(()=>validateWorkflow(rec('plan','plan',{patientId:'p1',status:'Rascunho'}),rec('plan','plan',{patientId:'p1',status:'Ativo'}),rows,a),/revisão/);
const eq=rec('eq','equipment',{status:'Disponível'}),course=rec('c','course',{name:'Formação'});
const booking=rec('b','equipmentReservation',{equipmentId:'eq',therapist:'t1',date:'2026-09-19',time:'09:00',duration:45,status:'Reservada'});
validateWorkflow(booking,undefined,[...rows,eq],a);
assert.throws(()=>validateWorkflow(booking,{...booking,data:{...booking.data,therapist:'t2'}},[...rows,eq],a),/próprios/);
assert.throws(()=>validateWorkflow({...booking,data:{...booking.data,time:'23:45'}},undefined,[...rows,eq],a),/Horário/);
assert.throws(()=>validateWorkflow({...booking,data:{...booking.data,equipmentId:'missing'}},undefined,rows,a),/Equipamento/);
const enrollment=rec('en','trainingEnrollment',{courseId:'c',therapist:'t1',date:'2026-09-19',status:'Inscrito'});
validateWorkflow(enrollment,undefined,[...rows,course],a);
assert.throws(()=>validateWorkflow({...enrollment,id:'duplicate'},undefined,[...rows,course,enrollment],a),/Já existe/);
assert.throws(()=>validateWorkflow(rec('campaign','campaign',{name:'Teste',status:'Preparada'}),undefined,rows,a),/direção/);
const autonomous=rec('as','autonomousSession',{patientId:'p1',date:'2026-09-19',duration:10,correct:5,error:2,status:'Concluída',source:'app'});
validateWorkflow(autonomous,undefined,rows,a);assert.equal(autonomous.data.source,'Registo manual pelo profissional');
assert.throws(()=>validateWorkflow({...autonomous,data:{...autonomous.data,prescriptionId:'foreign'}},undefined,[...rows,rec('foreign','prescription',{patientId:'p2'})],a),/prescrição/);
assert.equal(visible(rec('other','autonomousSession',{patientId:'p2'}),a,rows),false);
assert.equal(visible(rec('other','trainingEnrollment',{therapist:'t2'}),a,rows),false);
assert.equal(visible(enrollment,director,rows),true);
console.log('14 additional plan, TPC, reservation and training checks passed');
