import type {Rec} from './model';
export const lisbonNow=(date=new Date())=>{const p=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Lisbon',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(date);return {date:p.slice(0,10),time:p.slice(11,16)}};
export const nextDay=(date:string)=>new Date(Date.parse(date+'T12:00:00Z')+86400000).toISOString().slice(0,10);
export const activePlans=(rows:Rec[],patientId:string)=>rows.filter(r=>r.kind==='plan'&&r.data.patientId===patientId&&['Ativo','Aprovado'].includes(r.data.status));
export function goalEvidence(rows:Rec[],plan:Rec,goal:any){
 const lineage=new Set([plan.id]);let ancestor=plan;while(ancestor.data.basePlanId&&!lineage.has(ancestor.data.basePlanId)){const previous=rows.find(r=>r.kind==='plan'&&r.id===ancestor.data.basePlanId);const old=previous?.data.goals?.find((g:any)=>g.id===goal.id);if(!previous||!old||old.name!==goal.name||old.criteria!==goal.criteria)break;lineage.add(previous.id);ancestor=previous}
 const entries=rows.filter(r=>r.kind==='session'&&r.data.status==='Concluída'&&r.data.patientId===plan.data.patientId).flatMap(r=>(r.data.goalResults||[]).filter((g:any)=>lineage.has(g.planId)&&g.goalId===goal.id&&g.observed!==false).map((g:any)=>({date:r.data.date,sessionId:r.id,...g}))).sort((a:any,b:any)=>a.date.localeCompare(b.date)||a.sessionId.localeCompare(b.sessionId));
 const measured=entries.filter((x:any)=>Number(x.attempts)>0);const recent=measured.slice(-3);const n=recent.reduce((s:number,x:any)=>s+x.attempts,0);const rate=n?Math.round(recent.reduce((s:number,x:any)=>s+x.correct,0)/n*100):null;
 const target=Number(goal.targetPercent), required=Number(goal.requiredSessions);const configured=Number.isFinite(target)&&target>0&&target<=100&&Number.isInteger(required)&&required>0;const met=configured&&measured.length>=required&&measured.slice(-required).every((g:any)=>g.correct/g.attempts*100>=target);
 const falling=measured.length>=3&&measured.slice(-3).every((g:any,i:number,a:any[])=>i===0||g.correct/g.attempts<a[i-1].correct/a[i-1].attempts);
 return {entries,rate,met,suggestion:!configured?'Definir o critério quantitativo da meta com a terapeuta.':met?'Critério atingido nas sessões exigidas: validar aquisição e próximo objetivo.':falling?'Desempenho em descida nas últimas três medições: rever estratégias e condições.':entries.length?'Manter observação e comparar nas mesmas condições.':'Recolher uma observação inicial deste objetivo.'};
}
export function preparation(rows:Rec[],appointment:Rec){
 const patient=rows.find(r=>r.id===appointment.data.patientId&&r.kind==='patient');
 const sessions=rows.filter(r=>r.kind==='session'&&r.data.patientId===appointment.data.patientId&&r.data.status==='Concluída'&&r.data.date<=appointment.data.date).sort((a,b)=>b.data.date.localeCompare(a.data.date)).slice(0,3);
 const plans=activePlans(rows,appointment.data.patientId);
 const observations=rows.filter(r=>r.data.patientId===appointment.data.patientId&&(r.kind==='communication'&&r.data.type==='Informação da família'||r.kind==='familyMessage'&&r.data.direction==='parent')).sort((a,b)=>String(b.data.date||'').localeCompare(String(a.data.date||''))).slice(0,3);
 return {patient,plans,sessions,body:[`${patient?.data.name||'Paciente'} · ${appointment.data.date} às ${appointment.data.time}`,'OBJETIVOS ATIVOS',...plans.flatMap(p=>(p.data.goals||[]).map((g:any)=>`${g.name} — ${g.criteria||'Critério por definir'}\n${goalEvidence(rows,p,g).suggestion}`)),plans.length?'':'Sem plano ativo: definir ou aprovar o plano.', 'ÚLTIMAS SESSÕES',...sessions.map(s=>`${s.data.date}: ${s.data.summary||s.data.soap?.o||'Sem sumário'}\nPróximo passo registado: ${s.data.nextSteps||s.data.soap?.p||'Não registado'}\nMateriais: ${s.data.materials||'Não indicados'}`),sessions.length?'':'Sem sessões anteriores registadas.','ADENDAS',...rows.filter(r=>r.kind==='sessionAmendment'&&sessions.some(s=>s.id===r.data.sessionId)).map(r=>r.data.date+': '+r.data.body),'ESTRATÉGIAS REGISTADAS',...(patient?.data.strategyItems||[]).filter((s:any)=>!s.archived).map((s:any)=>`${s.category==='works'?'Funciona':'Evitar / rever'}: ${s.body}`),'INFORMAÇÃO DA FAMÍLIA',...observations.map(r=>r.data.body),'Fontes: '+[...sessions,...plans,...observations].map(r=>r.kind+' '+r.id+' (v'+r.version+')').join(', ')].filter(Boolean).join('\n\n')};
}
export function presence(rows:Rec[],therapist:string,date=lisbonNow().date){const last=rows.filter(r=>r.kind==='attendance'&&r.data.therapist===therapist&&r.data.date===date).sort((a,b)=>(b.data.recordedAt||b.data.time).localeCompare(a.data.recordedAt||a.data.time))[0];return !last?'Sem check-in':last.data.type==='Saída'?'Saiu':last.data.type==='Pausa'?'Em pausa':'Presente'}
export function attendanceIssues(rows:Rec[],now=lisbonNow()){
 return rows.filter(r=>r.kind==='team'&&r.data.status!=='Ausente').flatMap(t=>{const ap=rows.filter(r=>r.kind==='appointment'&&r.data.therapist===t.id&&r.data.date===now.date&&!['Cancelada','Falta'].includes(r.data.status)).sort((a,b)=>a.data.time.localeCompare(b.data.time));const weekday=new Date(now.date+'T12:00').getDay();const scheduled=(String(t.data.workDays||'1,2,3,4,5').split(',').includes(String(weekday))?t.data.startTime:'')||ap[0]?.data.time;const absent=rows.some(r=>r.kind==='leave'&&r.data.therapist===t.id&&r.data.status==='Aprovado'&&r.data.date<=now.date&&r.data.endDate>=now.date);if(!scheduled||absent)return [];const limit=Number(scheduled.slice(0,2))*60+Number(scheduled.slice(3))+Number(t.data.graceMinutes??10);const m=Number(now.time.slice(0,2))*60+Number(now.time.slice(3));const first=rows.filter(r=>r.kind==='attendance'&&r.data.therapist===t.id&&r.data.date===now.date&&r.data.type==='Entrada').sort((a,b)=>a.data.time.localeCompare(b.data.time))[0];const late=first&&(Number(first.data.time.slice(0,2))*60+Number(first.data.time.slice(3))>limit);return !first&&m>limit||late?[{id:`attendance-${t.id}-${now.date}`,therapist:t.id,title:`${t.data.name}: ${first?'entrada com atraso':'check-in por confirmar'}`,detail:`Previsto ${scheduled}. ${first?'Entrada '+first.data.time:'Sem entrada registada; confirmar com a terapeuta.'}`}]:[]})
}
export function careTasks(rows:Rec[],date=lisbonNow().date){return [
 ...rows.filter(r=>r.kind==='appointment'&&r.data.date<=date&&r.data.status==='Concluída'&&!rows.some(s=>s.kind==='session'&&s.data.appointmentId===r.id&&s.data.status==='Concluída')).map(r=>({id:r.id,patientId:r.data.patientId,title:'Sumário por concluir',detail:r.data.date+' · '+r.data.time})),
 ...rows.filter(r=>r.kind==='session'&&r.data.status==='Rascunho').map(r=>({id:r.id,patientId:r.data.patientId,title:'Sumário em rascunho',detail:r.data.date})),
 ...rows.filter(r=>r.kind==='plan'&&['Aprovado','Ativo'].includes(r.data.status)&&r.data.reviewDate&&r.data.reviewDate<=date).map(r=>({id:r.id,patientId:r.data.patientId,title:'Plano por rever',detail:r.data.name})),
 ...rows.filter(r=>r.kind==='delivery'&&['Falhou','Por configurar','Resultado desconhecido'].includes(r.data.status)).map(r=>({id:r.id,patientId:r.data.patientId,title:'Partilha por verificar',detail:r.data.status})),
 ...rows.filter(r=>r.kind==='plan'&&r.data.basePlanId&&r.data.status==='Por aprovar').map(r=>({id:r.id,patientId:r.data.patientId,title:'Proposta de alteração',detail:r.data.name}))
]}
