import type {Rec} from './model';
import {completedSessions} from './session-report';
import {isOverdueIncome} from './finance';
import {appointmentAvailability} from './scheduling';
export const minutes=(s:string)=>Number(s?.slice(0,2)||0)*60+Number(s?.slice(3,5)||0);
export function sessionAccuracy(r:Rec){const d=r.data;const total=Number(d.correct||0)+Number(d.help||0)+Number(d.error||0);return total?Math.round(Number(d.correct||0)/total*100):null}
export function nps(rows:Rec[],audience:string,therapist?:string){const a=rows.filter(r=>r.kind==='feedback'&&r.data.audience===audience&&(!therapist||r.data.therapist===therapist));return a.length?Math.round(100*(a.filter(r=>r.data.score>=9).length-a.filter(r=>r.data.score<=6).length)/a.length):null}
export function workedMinutes(rows:Rec[],therapist:string,month:string){let total=0;const dates=[...new Set(rows.filter(r=>r.kind==='attendance'&&r.data.therapist===therapist&&r.data.date?.startsWith(month)).map(r=>r.data.date))];for(const date of dates){let start:number|null=null;const events=rows.filter(r=>r.kind==='attendance'&&r.data.therapist===therapist&&r.data.date===date).sort((a,b)=>(a.data.recordedAt||a.data.time).localeCompare(b.data.recordedAt||b.data.time));for(const e of events){if(['Entrada','Retoma'].includes(e.data.type)){if(start===null)start=minutes(e.data.time)}else if(['Pausa','Saída'].includes(e.data.type)&&start!==null){total+=Math.max(0,minutes(e.data.time)-start);start=null}}}return total}
export function flags(rows:Rec[],date=new Date().toISOString().slice(0,10)){const patients=rows.filter(r=>r.kind==='patient'&&r.data.status!=='Arquivado');const out:any[]=[];for(const p of patients){const ap=rows.filter(r=>r.kind==='appointment'&&r.data.patientId===p.id&&r.data.date<=date).sort((a,b)=>b.data.date.localeCompare(a.data.date));const misses=ap.slice(0,4).filter(a=>a.data.status==='Falta').length;if(misses>=2)out.push({id:'miss-'+p.id,patientId:p.id,name:'Faltas repetidas',type:'Padrão de faltas',detail:misses+' faltas nas últimas 4 marcações',priority:3});const sessions=completedSessions(rows,p.id).filter(r=>r.data.date&&r.data.date<=date).reverse();if(sessions.length){const days=Math.floor((Date.parse(date)-Date.parse(sessions[0].data.date))/86400000);if(days>=14)out.push({id:'inactive-'+p.id,patientId:p.id,name:'Acompanhamento sem atividade recente',type:'Inatividade',detail:days+' dias sem sessão registada',priority:2});const recent=sessions.slice(0,3).map(sessionAccuracy).filter((n):n is number=>n!==null);if(recent.length===3&&recent.every(n=>n>=80))out.push({id:'advance-'+p.id,patientId:p.id,name:'Rever possibilidade de progressão',type:'Transição',detail:'Precisão ≥80% em 3 sessões. Confirmar generalização e objetivos.',priority:1});if(recent.length===3&&recent[0]+20<recent[2])out.push({id:'regression-'+p.id,patientId:p.id,name:'Queda de desempenho a rever',type:'Clínico',detail:'Diferença de mais de 20 pontos entre registos. Confirmar contexto e comparabilidade.',priority:3});}const invoices=rows.filter(r=>r.data.patientId===p.id&&isOverdueIncome(r,date));if(invoices.length)out.push({id:'payment-'+p.id,patientId:p.id,name:'Pagamentos pendentes',type:'Financeiro',detail:invoices.length+' movimentos por regularizar',priority:2});}return out.sort((a,b)=>b.priority-a.priority)}
export function availableSlots(rows:Rec[],data:any){const out:string[]=[];for(let t=8*60;t<=19*60-Number(data.duration||45);t+=15){const time=String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');if(!appointmentAvailability(rows,{...data,time,duration:Number(data.duration||45),status:'Esperado'},data.id))out.push(time)}return out}
export function distanceKm(a:{lat:number;lng:number},b:{lat:number;lng:number}){const rad=(x:number)=>x*Math.PI/180;const dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng);const h=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
export function plannedMinutes(rows:Rec[],therapist:string,month:string){return rows.filter(r=>r.kind==='appointment'&&r.data.therapist===therapist&&r.data.date?.startsWith(month)&&r.data.status!=='Cancelada').reduce((s,r)=>s+Number(r.data.duration||0),0)}
