import {env} from 'cloudflare:workers';
import {serviceConfig} from './supabase-http';
import {db,AppError,type Identity} from './server';

const bytes=new TextEncoder();
const base64=(value:Uint8Array)=>btoa(String.fromCharCode(...value));
const decode=(value:string)=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
export async function seal(value:unknown,context:string){const key=await encryptionKey(),iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:bytes.encode(context)},key,bytes.encode(JSON.stringify(value)));return base64(iv)+'.'+base64(new Uint8Array(encrypted));}
export async function unseal(value:string,context:string){const [iv,body]=value.split('.');const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(iv),additionalData:bytes.encode(context)},await encryptionKey(),decode(body));return JSON.parse(new TextDecoder().decode(clear));}
async function encryptionKey(){const secret=String((env as any).INTEGRATIONS_ENCRYPTION_KEY||serviceConfig().SUPABASE_SECRET_KEY);const material=await crypto.subtle.digest('SHA-256',bytes.encode('bem-crescer-integrations-v1:'+secret));return crypto.subtle.importKey('raw',material,'AES-GCM',false,['encrypt','decrypt']);}
export const googleReady=()=>Boolean((env as any).GOOGLE_CLIENT_ID&&(env as any).GOOGLE_CLIENT_SECRET);
export async function googleConnection(a:Identity){const row=await db().prepare('SELECT payload,version FROM integration_connections WHERE clinic=? AND user_id=? AND provider=?').bind(a.tenant,a.user.userId,'google').first<any>();return row?{...await unseal(row.payload,a.tenant+':'+a.user.userId),version:row.version}:null;}
export async function saveGoogleConnection(a:Identity,tokens:any,version:number){const payload=await seal(tokens,a.tenant+':'+a.user.userId),now=new Date().toISOString();const result=version?await db().prepare('UPDATE integration_connections SET payload=?,version=version+1,updated=? WHERE clinic=? AND user_id=? AND provider=? AND version=?').bind(payload,now,a.tenant,a.user.userId,'google',version).run():await db().prepare('INSERT OR IGNORE INTO integration_connections(clinic,user_id,provider,payload,version,updated) VALUES(?,?,?,?,1,?)').bind(a.tenant,a.user.userId,'google',payload,now).run();if(!result.meta.changes)throw new AppError('A ligação mudou. Atualize e tente novamente.',409);}
export async function removeGoogleConnection(a:Identity){await db().prepare('DELETE FROM integration_connections WHERE clinic=? AND user_id=? AND provider=?').bind(a.tenant,a.user.userId,'google').run();}
export async function googleToken(a:Identity){let connection=await googleConnection(a);if(!connection)throw new AppError('Ligue primeiro a sua conta Google.',409);if(connection.expiresAt>Date.now()+60000)return connection.accessToken;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:(env as any).GOOGLE_CLIENT_ID,client_secret:(env as any).GOOGLE_CLIENT_SECRET,refresh_token:connection.refreshToken,grant_type:'refresh_token'}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new AppError('Volte a ligar a sua conta Google.',409);const x:any=await r.json();await saveGoogleConnection(a,{accessToken:x.access_token,refreshToken:x.refresh_token||connection.refreshToken,expiresAt:Date.now()+x.expires_in*1000},connection.version);return x.access_token;}
export async function googleEventId(a:Identity,id:string){const digest=await crypto.subtle.digest('SHA-256',bytes.encode(a.tenant+':'+a.user.userId+':'+id));return 'bc'+Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');}
