export type Rec = {
    id: string;
    kind: string;
    version: number;
    data: Record<string, any>;
    author?: string;
};
export const districts = ['D2 · Coliseu dos Sons', 'D3 · Conservatório dos Sons', 'D4 · Mercado', 'D5 · Jardim das Letras'];
export const sources = [{ name: 'Painel Diretor de Clínica', url: 'https://drive.google.com/file/d/1iFpateuJoeg8FN3XZik5zKy72_sOG_2Y/view' }, { name: 'Painel Terapeuta de Clínica', url: 'https://drive.google.com/file/d/1F3h2aL9IryYQBzGQ3OXaFxXluo_3VBM3/view' }, { name: 'Linguar · Gameplay', url: 'https://docs.google.com/spreadsheets/d/1FNnD4owz2YvWXvcJa0YMxfc0UErntvwucVWqk9i7x1U/edit' }, { name: 'D2 · Conteúdos editoriais', url: 'https://docs.google.com/spreadsheets/d/19JXfEc9vVnXRN3qCZfLe2KW_O6akhpDlIdg9hdmH2Us/edit' }, { name: 'D3 · Conteúdos editoriais', url: 'https://docs.google.com/spreadsheets/d/1la92H7422ysU7op79j5j3HkoyHKtOxOK5-PaCAN2w9E/edit' }, { name: 'D4 · Conteúdos editoriais', url: 'https://docs.google.com/spreadsheets/d/1Xxf5wvGaBAF2P-BoSb-Fwa0TjVNfbWjjVClw7sY1-2w/edit' }, { name: 'D5 · Conteúdos editoriais', url: 'https://docs.google.com/spreadsheets/d/1n91Z8cbbrSTSvD1cFih7mk2y01EzS5metGYpvXMbTbk/edit' }];
export const clinicNav = [['Operação (Agora)', 'overview', 'flow', 'rooms', 'agenda'], ['Clínica', 'patients', 'families', 'sessions', 'preparation', 'careInbox', 'family', 'team', 'attendance', 'supervision', 'ai'], ['Escolas', 'schools', 'itinerary'], ['Equipa', 'leave', 'chat'], ['Administrativo', 'communications', 'finance', 'subscription', 'training', 'materials', 'analytics', 'feedback', 'alerts', 'archive']];
export const therapistNav = [['Prática clínica', 'overview', 'agenda', 'patients', 'families', 'preparation', 'careInbox', 'family', 'sessions', 'reports', 'alerts'], ['Recursos', 'library', 'training', 'backpack'], ['Na clínica', 'itinerary', 'attendance', 'chat']];
export const labels: Record<string, string> = { families:'Crianças e famílias', pilot:'Teste e verificação', family:'Área dos pais', preparation:'Preparação de sessões',careInbox:'Avisos e partilhas',autonomous:'TPC / Autónomas', overview: 'Visão geral', flow: 'Live Flow', rooms: 'Salas & recursos', agenda: 'Agenda', patients: 'Pacientes 360º', team: 'Gestão de equipa', attendance: 'Assiduidade', supervision: 'Supervisão & avaliação', ai: 'Ferramentas IA', schools: 'Monitor de escolas', itinerary: 'Itinerário escolar', leave: 'Férias & ausências', chat: 'Chat da equipa', communications: 'Comunicações', finance: 'Financeiro', subscription: 'Subscrição', training: 'Formação', materials: 'Materiais', analytics: 'Analytics', feedback: 'NPS & feedback', alerts: 'Alertas', archive: 'Arquivo', prescriptions: 'Prescrições', sessions: 'Sessões', reports: 'Relatórios', library: 'Biblioteca', backpack: 'Mochila digital' };
export function sampleRecords(date = new Date().toISOString().slice(0, 10)): Rec[] {
    let rows: Rec[] = [];
    const add = (id: string, kind: string, data: any) => rows.push({ id, kind, data, version: 1, author: 't1' });
    [['t1', 'Mariana Alves', 'MA'], ['t2', 'Inês Ribeiro', 'IR'], ['t3', 'João Ferreira', 'JF']].forEach(([id, name, initials]) => add(id, 'team', { name, initials, email: '', specialty: 'Terapia da Fala', hours: 35, status: 'Ativo' }));
    ['Sala Girassol', 'Sala Horizonte', 'Sala Mar'].forEach((name, i) => add('room' + i, 'room', { name, capacity: 2, status: 'Disponível' }));
    [['Leonor Martins', 6, 'Perturbação dos sons da fala', 0, 72, 't1'], ['Tomás Silva', 5, 'Perturbação da linguagem', 2, 48, 't1'], ['Matilde Costa', 8, 'Dificuldades de leitura', 3, 85, 't2'], ['Duarte Santos', 7, 'Consciência fonológica', 1, 61, 't3'], ['Beatriz Rocha', 5, 'Perturbação dos sons da fala', 0, 38, 't1'], ['Afonso Oliveira', 9, 'Dificuldades de escrita', 3, 67, 't2']].forEach(([name, age, diagnosis, d, progress, therapist], i) => add('p' + i, 'patient', { name, age, diagnosis, district: districts[Number(d)], progress, therapist, status: 'Ativo', guardian: 'Responsável de demonstração', school: 'Escola do Parque', contact: '', objectives: 'Consolidar as competências trabalhadas e promover a generalização.', zones: [districts[Number(d)]], needsAssessment: i === 1 }));
    [['09:00', 'p0', 't1', 'Concluída', 'Clínica'], ['10:00', 'p1', 't1', 'Concluída', 'Escola'], ['11:00', 'p2', 't2', 'Concluída', 'Clínica'], ['14:00', 'p0', 't1', 'Em sessão', 'Clínica'], ['14:00', 'p3', 't3', 'Sala de espera', 'Clínica'], ['15:00', 'p4', 't1', 'Esperado', 'Clínica'], ['15:30', 'p5', 't2', 'Esperado', 'Online'], ['16:00', 'p1', 't1', 'Esperado', 'Clínica']].forEach(([time, patientId, therapist, status, context], i) => add('a' + i, 'appointment', { date, time, patientId, therapist, status, context, duration: 45, room: context === 'Clínica' ? 'room' + (therapist === 't1' ? 0 : therapist === 't2' ? 1 : 2) : '', type: 'Sessão' }));
    add('plan0', 'plan', { patientId: 'p0', name: 'Generalização do som /s/', body: 'Produzir /s/ em palavras e frases com apoio progressivamente reduzido.', status: 'Por aprovar' });
    add('plan1', 'plan', { patientId: 'p1', name: 'Compreensão de instruções', body: 'Compreender instruções de dois passos em contexto funcional.', status: 'Por aprovar' });
    add('rx0', 'prescription', { patientId: 'p0', district: districts[0], name: 'Som /s/ em palavras', skill: 'Articulação', exercises: 'Seleção no banco por confirmar', frequency: 3, repetitions: 10, duration: 8, targets: '/s/', words: 'sapo, sopa, sino', status: 'Rascunho', sync: 'Não ligado à app da criança' });
    add('alert0', 'alert', { patientId: 'p4', name: 'Rever a regularidade do acompanhamento', body: 'Exemplo: duas faltas consecutivas. Confirmar com a família.', type: 'Padrão de faltas', status: 'Por rever' });
    add('alert1', 'alert', { patientId: 'p1', name: 'Plano à espera de revisão', body: 'Rever objetivos antes da próxima sessão.', type: 'Clínico', status: 'Por rever' });
    add('school0', 'school', { name: 'Escola do Parque', contact: '', address: 'Lisboa', teacher: 'Contacto por preencher', status: 'Parceira' });
    add('visit0', 'visit', { name: 'Apoio na Escola do Parque', school: 'Escola do Parque', date, time: '10:00', therapist: 't1', status: 'Concluído', km: 8, notes: 'Registo de demonstração; sem localização GPS.' });
    add('inv0', 'invoice', { name: 'Sessão de setembro', patientId: 'p0', date, amount: 45, status: 'Pago', type: 'Receita' });
    add('inv1', 'invoice', { name: 'Sessão de setembro', patientId: 'p1', date, amount: 45, status: 'Por pagar', type: 'Receita' });
    add('inv2', 'invoice', { name: 'Materiais de sessão', date, amount: 18, status: 'Pago', type: 'Custo' });
    add('leave0', 'leave', { name: 'Férias', therapist: 't2', date, endDate: date, status: 'Por aprovar', notes: 'Pedido de exemplo' });
    add('material0', 'material', { name: 'Cartões de discriminação auditiva', category: 'Materiais', district: districts[0], body: 'Selecione os pares-alvo a partir do banco editorial D2. Recurso de demonstração.', quantity: 8, status: 'Disponível', visibility: 'Clínica' });
    add('feedback0', 'feedback', { name: 'Família · setembro', therapist: 't1', audience: 'Pais', score: 9, notes: 'Exemplo de feedback', date });
    add('feedback1', 'feedback', { name: 'Criança · setembro', therapist: 't1', audience: 'Criança', score: 8, notes: 'Escala de demonstração; não é avaliação clínica', date });
    add('course0', 'course', { name: 'Integração na clínica Bem Crescer', body: 'Consultar os painéis e as regras de prescrição nos recursos do projeto.', hours: 2, progress: 0, status: 'Por iniciar' });
    return rows;
}
