import {env} from 'cloudflare:workers';
import {db,failure} from '@/lib/server';
import {verifyEmailWebhook,emailEventStatus,shouldApplyEmailEvent} from '@/lib/email-events';
export async function POST(req:Request){const secret=(env as any).RESEND_WEBHOOK_SECRET;if(!secret)return new Response('Unavailable',{status:503});const body=await req.text();if(body.length>100000)return new Response('Too large',{status:413});let verified;try{verified=await verifyEmailWebhook(body,req.headers,secret)}catch{return new Response('Invalid signature',{status:401})}
 try{const {id,event}=verified,providerId=event.data?.email_id,type=event.type,status=emailEventStatus(type),date=event.created_at;if(!status||typeof providerId!=='string'||providerId.length>160||typeof date!=='string')return Response.json({ok:true});const rows=await db().prepare("SELECT * FROM records WHERE kind='delivery' AND json_extract(data,'$.providerId')=?").bind(providerId).all<any>();for(const row of rows.results){const data=JSON.parse(row.data),now=new Date().toISOString(),eventId='resend-event:'+id;if(!shouldApplyEmailEvent(data,type,date))continue;const operation=crypto.randomUUID();const updated={...data,status,emailEventAt:date,emailEventType:type,mutationId:operation};const noticeId=row.clinic+':email-event-'+id,notice={name:'Entrega do sumário: '+status,type:'delivery',directorOnly:true,patientId:data.patientId,deliveryId:row.id.slice(row.clinic.length+1),body:'O serviço de email comunicou: '+status+'. Consulte o histórico de partilhas.',createdAt:now};const result=await db().batch([
 db().prepare('UPDATE records SET data=?,version=version+1,updated=? WHERE id=? AND clinic=? AND version=? AND NOT EXISTS(SELECT 1 FROM audit WHERE id=?)').bind(JSON.stringify(updated),now,row.id,row.clinic,row.version,eventId),
 db().prepare("INSERT OR IGNORE INTO records(id,clinic,kind,data,author,version,updated) SELECT ?,?,'careNotice',?,?,1,? WHERE EXISTS(SELECT 1 FROM records WHERE id=? AND json_extract(data,'$.mutationId')=?)").bind(noticeId,row.clinic,JSON.stringify(notice),'email-provider',now,row.id,operation),
 db().prepare("INSERT OR IGNORE INTO audit(id,clinic,actor,action,record_id,created) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM records WHERE id=? AND json_extract(data,'$.mutationId')=?)").bind(eventId,row.clinic,'email-provider',type,row.id,now,row.id,operation)
 ]);if(!result[0].meta.changes&&!await db().prepare('SELECT id FROM audit WHERE id=?').bind(eventId).first())throw Error('Concurrent webhook update');}return Response.json({ok:true});}catch(e){return failure(e)}}
