import {eligiblePatient} from '@/lib/family';
import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {db,identity,ensureClinic,allRecords,visible,checkOrigin,AppError,failure} from '@/lib/server';
import {atomicSave,insertRecord,notification,mailReady,runClinic,sendDelivery} from '@/lib/care-server';
import {lisbonNow} from '@/lib/care';
import type {Rec} from '@/lib/model';
const text=z.string().max(20000);const token=z.string().regex(/^[\w-]+$/).max(120);
const resultSchema=z.object({planId:token,goalId:token,observed:z.boolean(),correct:z.number().int().min(0).max(10000),attempts:z.number().int().min(0).max(10000),help:z.number().int().min(0).max(10000),note:z.string().max(2000)});
export async function GET(req:Request){try{const a=await identity(req);await ensureClinic(a);const ready=await mailReady(a);return Response.json({emailReady:ready,schedulerReady:Boolean((env as any).CARE_CRON_SECRET)||(env as any).CARE_SCHEDULER_MODE==='cloudflare',schedulerMode:(env as any).CARE_SCHEDULER_MODE==='cloudflare'?'cloudflare':'external',preparationEmailEnabled:(env as any).CARE_TEAM_EMAIL_ENABLED==='true'&&ready,timezone:'Europe/Lisbon'},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(req:Request){try{checkOrigin(req);const a=await identity(req);await ensureClinic(a);const raw=await req.text();if(new TextEncoder().encode(raw).length>1000000)throw new AppError('Registo demasiado grande.');const input=JSON.parse(raw);if(input.action!=='session'&&raw.length>100000)throw new AppError('Registo demasiado grande.');const rows=await allRecords(a);const get=(id:string,kind?:string)=>{const r=rows.find(r=>r.id===id&&(!kind||r.kind===kind));if(!r||!visible(r,a,rows))throw new AppError('Registo indisponível.',403);return r};const action=input.action,now=new Date().toISOString();
 if(action==='refresh'){await runClinic(a);return Response.json({ok:true})}
 if(action==='session'){
 const x=z.object({appointmentId:token,version:z.number().int().nonnegative(),summary:text,nextSteps:text,materials:text,familySummary:text,internalNote:text,goalResults:z.array(resultSchema),final:z.boolean()}).parse(input);
 const ap=get(x.appointmentId,'appointment'),patient=get(ap.data.patientId,'patient');if(a.role!=='director'&&ap.data.therapist!==a.therapist)throw new AppError('Esta sessão está atribuída a outra terapeuta.',403);
 if(['Cancelada','Falta'].includes(ap.data.status))throw new AppError('Não pode registar uma sessão cancelada ou uma falta.');if(ap.data.date>lisbonNow().date&&x.final)throw new AppError('Não pode concluir uma sessão futura.');
 const id='care-'+ap.id,prev=rows.find(r=>r.id===id);if(prev&&prev.kind!=='session')throw new AppError('Identificador de sessão em conflito.',409);if(prev?.data.patientId&&prev.data.patientId!==ap.data.patientId)throw new AppError('O paciente da marcação foi alterado. Reveja o acompanhamento.',409);if(prev?.data.status==='Concluída')throw new AppError('Sumário concluído. Acrescente uma adenda para preservar o original.');if(prev&&prev.version!==x.version)throw new AppError('O rascunho mudou. Atualize antes de guardar.',409);
 if(x.final&&!x.summary.trim())throw new AppError('Escreva o sumário antes de concluir.');
 // A draft may reference a plan subsequently revised or closed. Keep its saved
 // observations with the original goal identity; never remap them onto new goals.
 const previousGoals:any[]=Array.isArray(prev?.data.goalResults)?prev.data.goalResults:[];
 const previousGoalByKey=new Map(previousGoals.map(g=>[g.planId+':'+g.goalId,g]));
 const submitted=new Set(x.goalResults.map(g=>g.planId+':'+g.goalId));
 const incoming=[...x.goalResults,...previousGoals.filter(g=>!submitted.has(g.planId+':'+g.goalId))];
 const keys=new Set<string>();const goals=incoming.map(g=>{
  const p=get(g.planId,'plan'),goal=p.data.goals?.find((v:any)=>v.id===g.goalId),key=g.planId+':'+g.goalId;
  const previous=previousGoalByKey.get(key),active=['Ativo','Aprovado'].includes(p.data.status);
  if(keys.has(key)||p.data.patientId!==ap.data.patientId||active&&!goal||!active&&!previous)throw new AppError('Objetivo inválido ou plano já revisto. Reabra o rascunho para atualizar os objetivos.');
  keys.add(key);if(g.correct+g.help>g.attempts||g.observed&&g.attempts===0)throw new AppError('As tentativas devem incluir os acertos e as respostas com ajuda.');
  return {planId:g.planId,goalId:g.goalId,observed:g.observed,correct:g.correct,attempts:g.attempts,help:g.help,note:g.note,goalName:active?goal.name:previous.goalName||goal?.name||'Objetivo anterior',criteria:active?goal.criteria||'':previous.criteria||'',planVersion:active?p.version:previous.planVersion,historicalGoal:!active};
 });
 if(new Set(goals.map(g=>g.planId)).size>50)throw new AppError('Uma sessão pode registar objetivos de até 50 planos diferentes. O rascunho anterior foi preservado.');
 const r:Rec={id,kind:'session',version:x.version,data:{patientId:ap.data.patientId,therapist:ap.data.therapist,appointmentId:ap.id,date:ap.data.date,time:ap.data.time,duration:ap.data.duration,name:'Sumário · '+ap.data.date,status:x.final?'Concluída':'Rascunho',summary:x.summary,nextSteps:x.nextSteps,materials:x.materials,familySummary:x.familySummary,internalNote:x.internalNote,goalResults:goals,careSchema:1,correct:goals.filter(g=>g.observed).reduce((s,g)=>s+g.correct,0),help:goals.filter(g=>g.observed).reduce((s,g)=>s+g.help,0),error:goals.filter(g=>g.observed).reduce((s,g)=>s+g.attempts-g.correct-g.help,0),recordedBy:a.user.userId,updatedAt:now,...(x.final?{finalizedAt:now}:{})}};
 const saved=await atomicSave(a,r,prev,guard=>x.final?[db().prepare("UPDATE records SET data=json_set(data,'$.status','Concluída'),version=version+1,updated=? WHERE id=? AND clinic=? AND EXISTS(SELECT 1 FROM records WHERE id=? AND json_extract(data,'$.mutationId')=?)").bind(now,a.tenant+':'+ap.id,a.tenant,a.tenant+':'+id,guard.op),insertRecord(a,notification('session-'+id,{name:'Sumário concluído',patientId:ap.data.patientId,directorOnly:true,type:'session',body:'Registo de '+ap.data.date+' disponível no acompanhamento.',sessionId:id}),guard)]:[],[{id:ap.id,version:ap.version},{id:patient.id,version:patient.version},...Array.from(new Set(goals.map(g=>g.planId))).map(id=>({id,version:get(id,'plan').version}))]);return Response.json({record:saved});
 }
 if(action==='amend'){
 const session=get(input.sessionId,'session');const body=text.min(1).parse(input.body);const id=token.parse(input.id);if(session.data.status!=='Concluída')throw new AppError('Conclua o sumário antes de acrescentar adendas.');const r:Rec={id,kind:'sessionAmendment',version:0,data:{patientId:session.data.patientId,sessionId:session.id,body,date:now,name:'Adenda ao sumário',recordedBy:a.user.userId}};await atomicSave(a,r,undefined,g=>[insertRecord(a,notification('amend-'+id,{name:'Adenda ao sumário',patientId:r.data.patientId,directorOnly:true,type:'session',body:'Foi acrescentada uma adenda ao acompanhamento.'}),g)]);return Response.json({ok:true});
 }
 if(action==='prepareDelivery'){
 const x=z.object({id:token,sessionId:token,recipient:z.string().email().max(254),body:text.min(1),confirmed:z.literal(true)}).parse(input);const session=get(x.sessionId,'session'),patient=get(session.data.patientId,'patient');if(session.data.status!=='Concluída')throw new AppError('Conclua o sumário primeiro.');const email=x.recipient.toLowerCase().trim();if(!eligiblePatient(patient,email))throw new AppError('Confirme na ficha o email do responsável autorizado e a autorização de partilha.');
 const r:Rec={id:x.id,kind:'delivery',version:0,data:{name:'Sumário para a família',patientId:patient.id,sessionId:session.id,recipient:email,body:x.body,status:'Preparado',reviewedBy:a.user.userId,reviewedAt:now}};await atomicSave(a,r,undefined,g=>[insertRecord(a,notification('share-'+r.id,{name:'Partilha solicitada pela terapeuta',patientId:patient.id,directorOnly:true,type:'delivery',body:'Sumário revisto para '+email+'. O envio ainda não foi confirmado.',deliveryId:r.id}),g)],[{id:patient.id,version:patient.version},{id:session.id,version:session.version}]);return Response.json({record:r});
 }
 if(action==='sendEmail'){const d=get(input.id,'delivery');if(d.data.status!=='Preparado')throw new AppError('Este envio já foi processado.');const patient=get(d.data.patientId,'patient');if(!eligiblePatient(patient,d.data.recipient))throw new AppError('O destinatário autorizado mudou. Prepare uma nova partilha.');const status=await sendDelivery(a,d,patient);return Response.json({status});}
 if(action==='manualShared'){const d=get(input.id,'delivery');const patient=get(d.data.patientId,'patient');if(!eligiblePatient(patient,d.data.recipient))throw new AppError('A autorização do destinatário mudou. Prepare uma nova partilha.');if(d.data.status!=='Preparado')throw new AppError('A partilha já foi registada.');const channel=z.enum(['Email manual','Partilha do dispositivo','Outro canal autorizado']).parse(input.channel);await atomicSave(a,{...d,data:{...d.data,status:'Partilha declarada',channel,declaredAt:now,declaredBy:a.user.userId}},d,g=>[insertRecord(a,notification('sent-'+d.id,{name:'Partilha declarada pela terapeuta',patientId:d.data.patientId,directorOnly:true,type:'delivery',body:channel+' · '+d.data.recipient+'. Sem confirmação técnica de entrega.',deliveryId:d.id}),g)],[{id:patient.id,version:patient.version}]);return Response.json({ok:true});}
 if(action==='readNotice'){const n=get(input.id,'careNotice');const readBy=[...new Set([...(n.data.readBy||[]),a.user.userId])];await atomicSave(a,{...n,data:{...n.data,readBy}},n);return Response.json({ok:true});}
 if(action==='proposePlan'){const base=get(input.id,'plan');if(!['Ativo','Aprovado'].includes(base.data.status))throw new AppError('Só pode propor a revisão de um plano ativo.');const id=token.parse(input.proposalId);const r:Rec={id,kind:'plan',version:0,data:{...base.data,mutationId:undefined,name:base.data.name+' · proposta',status:'Rascunho',basePlanId:base.id,basePlanVersion:base.version,revisionReason:'',proposedBy:a.user.userId,proposedAt:now}};await atomicSave(a,r,undefined);return Response.json({record:{...r,version:1}});}
 if(action==='closePlan'){
 if(a.role!=='director')throw new AppError('A direção gere o encerramento dos planos.',403);
 const x=z.object({id:token,version:z.number().int().positive(),status:z.enum(['Concluído','Arquivado']),reason:text.trim().min(1)}).parse(input),base=get(x.id,'plan');
 if(base.version!==x.version)throw new AppError('O plano mudou entretanto. Atualize antes de o encerrar.',409);
 if(!['Ativo','Aprovado'].includes(base.data.status))throw new AppError('Só pode encerrar um plano aprovado ou ativo.');
 const snapshot:Rec={...base,id:'plan-snapshot-'+crypto.randomUUID(),kind:'planSnapshot',version:0,data:{...base.data,originalPlanId:base.id,originalPlanVersion:base.version,snapshotAt:now,snapshotReason:x.reason}};
 const r:Rec={...base,data:{...base.data,status:x.status,closedAt:now,closedBy:a.user.userId,closedReason:x.reason}};
 const saved=await atomicSave(a,r,base,g=>[insertRecord(a,snapshot,g),insertRecord(a,notification('closed-'+base.id+'-'+base.version,{name:'Plano '+(x.status==='Concluído'?'concluído':'arquivado'),patientId:base.data.patientId,therapist:rows.find(p=>p.id===base.data.patientId)?.data.therapist,type:'plan',body:x.reason,planId:base.id}),g)]);
 return Response.json({record:saved});
 }
 if(action==='approvePlan'){
 if(a.role!=='director')throw new AppError('A aprovação pertence à direção.',403);const proposal=get(input.id,'plan'),base=get(proposal.data.basePlanId,'plan');if(proposal.version!==z.number().int().positive().parse(input.version))throw new AppError('A proposta mudou entretanto. Atualize antes de aprovar.',409);if(!['Ativo','Aprovado'].includes(base.data.status)||proposal.data.patientId!==base.data.patientId||proposal.data.status!=='Por aprovar'||base.version!==proposal.data.basePlanVersion)throw new AppError('A proposta está desatualizada ou não foi submetida. Crie uma proposta a partir do plano atual.',409);
 const r:Rec={...proposal,data:{...proposal.data,status:'Ativo',approvedAt:now,approvedBy:a.user.userId}};const snapshot:Rec={...base,id:'plan-snapshot-'+crypto.randomUUID(),kind:'planSnapshot',version:0,data:{...base.data,originalPlanId:base.id,originalPlanVersion:base.version,snapshotAt:now}};
 // Snapshot + activation + retirement and audit are one guarded transaction.
 await atomicSave(a,r,proposal,guard=>[insertRecord(a,snapshot,guard),db().prepare("UPDATE records SET data=json_set(data,'$.status','Substituído','$.replacedBy',?),version=version+1,updated=? WHERE id=? AND EXISTS(SELECT 1 FROM records WHERE id=? AND json_extract(data,'$.mutationId')=?)").bind(proposal.id,now,a.tenant+':'+base.id,a.tenant+':'+proposal.id,guard.op),insertRecord(a,notification('approved-'+proposal.id,{name:'Revisão do plano aprovada',patientId:base.data.patientId,therapist:rows.find(x=>x.id===base.data.patientId)?.data.therapist,type:'plan',body:proposal.data.revisionReason||proposal.data.name}),guard)],[{id:base.id,version:base.version}]);return Response.json({ok:true});
 }
 throw new AppError('Ação desconhecida.');
}catch(e){if(e instanceof z.ZodError)return Response.json({error:'Preencha os campos obrigatórios e verifique os valores.'},{status:400});return failure(e)}}
