'use client';
import '../pais/parents.css';
import {useEffect,useState} from 'react';
import {usePro,Card,Pick,Empty,Badge,uid} from './shared';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {guardians} from '@/lib/patients';
import {eligiblePatient,familyTypes,publicationDraft} from '@/lib/family';
import {toast} from 'sonner';
export function FamilyHub({initialPatientId}:{initialPatientId?:string}={}){
 const p=usePro(),patients=p.records.filter(r=>r.kind==='patient'&&r.data.status!=='Arquivado');
 const [recipient,setRecipient]=useState(''),[patientId,setPatientId]=useState(initialPatientId||patients[0]?.id||''),[grants,setGrants]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[type,setType]=useState<string>(familyTypes[0]),[sourceId,setSourceId]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[fileId,setFileId]=useState(''),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState(''),[responses,setResponses]=useState<Record<string,string>>({});
 const patient=patients.find(r=>r.id===patientId),contacts=guardians(patient?.data||{}),email=contacts.some(g=>g.email===recipient)?recipient:contacts[0]?.email||'';
 const source=p.records.find(r=>r.id===sourceId);
 const sources=p.records.filter(r=>r.data.patientId===patientId&&(r.kind==='session'&&r.data.status==='Concluída'||r.kind==='plan'&&['Ativo','Aprovado'].includes(r.data.status)||['report','document'].includes(r.kind)));
 const linked=p.records.filter(r=>r.data.patientId===patientId),pubs=linked.filter(r=>r.kind==='familyPublication');
 async function refreshGrants(){if(!p.auth||!patientId)return;try{const r=await fetch('/api/family?view='+p.view+'&patientId='+patientId);const j:any=await r.json();if(!r.ok)throw Error(j.error);setGrants(j.grants)}catch(e:any){setError(e.message)}}
 useEffect(()=>{setGrants([]);setError('');refreshGrants()},[patientId,p.auth,p.view]);
 async function act(x:any){if(!p.auth){toast.info('Inicie sessão para guardar.');return false}setBusy(true);setError('');try{const r=await fetch('/api/family?view='+p.view,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({patientId,recipient:email,...x})});const j:any=await r.json();if(!r.ok)throw Error(j.error);p.reload();await refreshGrants();return true}catch(e:any){setError(e.message);return false}finally{setBusy(false)}}
 function choose(id:string){setSourceId(id);const r=sources.find(v=>v.id===id);setConfirmed(false);if(r){setTitle(r.data.name||'Sumário da sessão');setBody(publicationDraft(r,p.records));setType(r.kind==='session'?'Sumário':r.kind==='plan'?'Plano e objetivos':'Documento')}else{setTitle('');setBody('')}}
 return <div className="family-admin"><Card title="Ligação com os pais" sub="Agenda, conteúdos revistos e comunicação num espaço próprio para cada família." actions={<a href="/pais?demo=1" target="_blank" rel="noreferrer">Ver demonstração do painel ↗</a>}><Pick label="Paciente da área dos pais" value={patientId} change={(id:string)=>{setPatientId(id);setRecipient('');setSourceId('');setBody('');setTitle('');setFileId('');setConfirmed(false);setMessage('')}} options={patients.map(r=>({value:r.id,label:r.data.name}))}/>{patient&&<label>Responsável destinatário<Pick label="Responsável destinatário" value={email} change={(v:string)=>{setRecipient(v);setConfirmed(false);setMessage('')}} options={contacts.filter(g=>g.email).map(g=>({value:g.email,label:g.name+' · '+g.email+(g.shareAuthorized==='Sim'?'':' · sem autorização')}))}/></label>}{error&&<p className="notice" role="alert">{error}</p>}</Card>
 {!patient&&<Empty>Adicione uma criança em Crianças e famílias para configurar o painel dos responsáveis.</Empty>}{patient&&<><Card title="Acesso dos responsáveis" sub="Cada conta vê apenas os acompanhamentos autorizados para o seu email."><p>Endereço do painel: <a href="/pais" target="_blank" rel="noreferrer">/pais</a></p>{p.director?<><p className="small">Depois de ativar o acesso, o responsável inicia sessão em /pais com o seu email.</p><div className="actions"><Button variant="outline" onClick={()=>p.open('patient',patient)}>Editar responsáveis / autorizações</Button></div>{contacts.map(g=><div className="family-grant" key={g.id}><span>{g.name} · {g.email||'Sem email'} · Partilha: {g.shareAuthorized}</span><Button disabled={busy||!eligiblePatient(patient,g.email)||grants.some(x=>x.email===g.email&&x.enabled)} onClick={()=>act({action:'grant',email:g.email,enabled:true})}>Ativar acesso</Button></div>)}{grants.map(g=><p className="family-grant" key={g.id}><span>{g.email} · {g.enabled?'Ativo':'Revogado'}</span>{!!g.enabled&&<Button disabled={busy} variant="outline" onClick={()=>act({action:'grant',email:g.email,enabled:false})}>Revogar acesso</Button>}</p>)}</>:<p>A direção ativa e revoga o acesso. Pode preparar e publicar os conteúdos dos seus pacientes.</p>}</Card>
 <Card title="Publicar para os pais" sub="Reveja o texto e o anexo. Só esta versão será visível; alterações posteriores no registo clínico não a atualizam automaticamente."><label>Partir de um registo clínico (opcional)<Pick value={sourceId} change={choose} options={sources.map(r=>({value:r.id,label:(r.data.date||'')+' · '+(r.data.name||r.kind)}))}/></label><div className="family-form-grid"><label>Tipo<Pick value={type} change={(v:string)=>{setType(v);setConfirmed(false)}} options={[...familyTypes]}/></label><label>Título<Input value={title} maxLength={160} onChange={e=>{setTitle(e.target.value);setConfirmed(false)}}/></label></div><label>Texto destinado à família<Textarea rows={7} value={body} maxLength={20000} onChange={e=>{setBody(e.target.value);setConfirmed(false)}}/></label><label>Anexo do paciente (opcional)<Pick value={fileId} change={(id:string)=>{setFileId(id);setConfirmed(false)}} options={linked.filter(r=>r.kind==='file').map(r=>({value:r.id,label:r.data.name}))}/></label><label className="check-row"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>Revi o texto e todo o anexo para partilhar com {email||'o responsável autorizado'}.</label><Button disabled={busy||!confirmed||!body.trim()||!title.trim()||!type||!eligiblePatient(patient,email)} onClick={async()=>{if(await act({action:'publish',id:uid(),type,title,body,confirmed:true,...(source?{sourceId:source.id,sourceVersion:source.version}:{}),...(fileId?{fileId}:{})})){setBody('');setTitle('');setSourceId('');setFileId('');setConfirmed(false);toast.success('Publicado para os pais e clínica informada.')}}}>Publicar no painel dos pais</Button></Card>
 <Card title="Conteúdos publicados">{pubs.map(r=><article className="detail-box" key={r.id}><h3>{r.data.title} <Badge>{r.data.status}</Badge></h3><p className="small">{r.data.type} · {r.data.recipient} · {new Date(r.data.date).toLocaleString('pt-PT')}</p><p className="pre-wrap">{r.data.body}</p><small>{linked.some(x=>x.kind==='familyRead'&&x.data.publicationId===r.id)?'Leitura confirmada no painel':'Ainda sem confirmação de leitura'}</small>{r.data.status==='Publicado'&&<Button variant="outline" disabled={busy} onClick={()=>act({action:'withdraw',id:r.id})}>Retirar do painel</Button>}</article>)}{!pubs.length&&<Empty>Ainda não foi publicado conteúdo para esta família.</Empty>}</Card>
 <Card title="Pedidos sobre marcações" sub="Responder não altera a agenda. Faça o ajuste na marcação antes de confirmar a mudança à família.">{linked.filter(r=>r.kind==='familyRequest').map(r=><article className="detail-box" key={r.id}><h3>{r.data.type} <Badge>{r.data.status}</Badge></h3><p>{p.records.find(a=>a.id===r.data.appointmentId)?.data.date} · {p.records.find(a=>a.id===r.data.appointmentId)?.data.time}</p><p className="pre-wrap">{r.data.body}</p>{r.data.status==='Pendente'?<><Textarea aria-label="Resposta ao pedido" value={responses[r.id]||''} onChange={e=>setResponses({...responses,[r.id]:e.target.value})}/><div className="actions"><Button variant="outline" onClick={()=>{const ap=p.records.find(a=>a.id===r.data.appointmentId);if(ap)p.open('appointment',ap)}}>Abrir marcação</Button><Button disabled={busy||!responses[r.id]?.trim()} onClick={()=>act({action:'resolve',id:r.id,response:responses[r.id]})}>Guardar resposta</Button></div></>:<p>{r.data.response}</p>}</article>)}{!linked.some(r=>r.kind==='familyRequest')&&<Empty>Sem pedidos da família.</Empty>}</Card>
 <Card title="Mensagens com a família" sub="As mensagens ficam guardadas no acompanhamento e são visíveis à equipa autorizada.">{linked.filter(r=>r.kind==='familyMessage').sort((a,b)=>a.data.date.localeCompare(b.data.date)).map(r=><article className="detail-box" key={r.id}><small>{r.data.direction==='parent'?'Família':'Equipa clínica'} · {r.data.recipient} · {new Date(r.data.date).toLocaleString('pt-PT')}</small><p className="pre-wrap">{r.data.body}</p></article>)}<label>Mensagem<Textarea value={message} maxLength={6000} onChange={e=>setMessage(e.target.value)}/></label><Button disabled={busy||!message.trim()||!eligiblePatient(patient,email)} onClick={async()=>{if(await act({action:'message',id:uid(),body:message}))setMessage('')}}>Enviar para o painel dos pais</Button></Card></>}
 </div>;
}
