'use client';
import {useCallback,useEffect,useState} from 'react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Card,Empty,usePro} from './shared';
import {videoUrl} from '@/lib/calendar';

type IntegrationStatus={googleReady:boolean;googleConnected:boolean;gmailReady:boolean;gmailConnected:boolean;gmailSender:string;emailProvider:'gmail'|'resend'|'none';emailReady:boolean;webhookReady:boolean;preparationEmailEnabled:boolean};
export function Integrations(){const p=usePro(),[status,setStatus]=useState<IntegrationStatus|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{if(!p.auth)return;try{const r=await fetch('/api/integrations');const j=await r.json() as IntegrationStatus&{error?:string};if(!r.ok)throw Error(j.error||'Não foi possível consultar as ligações.');setStatus(j);setError('')}catch(e:any){setError(e.message)}},[p.auth]);
 useEffect(()=>{load();const params=new URLSearchParams(location.search),state=params.get('google'),gmail=params.get('gmail');if(state==='connected')toast.success('Conta Google ligada. Já pode sincronizar as marcações.');if(state==='failed')toast.error('A ligação Google não foi concluída. Tente novamente.');if(gmail==='connected')toast.success('Gmail da clínica ligado para enviar sumários e avisos.');if(gmail==='failed')toast.error('A ligação Gmail não foi concluída. A direção deve autorizar a conta da clínica.');},[load]);
 async function action(action:string){setBusy(true);setError('');try{const r=await fetch('/api/integrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const j:any=await r.json();if(!r.ok)throw Error(j.error);if(j.url)location.assign(j.url);else{await load();toast.success(action==='disconnectGmail'?'Gmail da clínica desligado.':'Conta Google desligada.')}}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function sync(id:string,version:number,meet:boolean){setBusy(true);try{const r=await fetch('/api/integrations/calendar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,version,meet})});const j:any=await r.json();if(!r.ok)throw Error(j.error);toast.success(j.message||'Calendário atualizado.');p.reload();setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const appointments=p.records.filter(r=>r.kind==='appointment'&&(p.director||r.data.therapist===p.me)&&r.data.date>=p.date).sort((a,b)=>(a.data.date+a.data.time).localeCompare(b.data.date+b.data.time));
 const gmailSender=status?.gmailSender||'centro.bemcrescer@gmail.com';
 const checking=p.auth&&!status&&!error;
 return <><Card title="Gmail da clínica" sub="Envie sumários revistos aos pais e avisos à equipa através do email da Bem Crescer.">
 {error&&<p role="alert" className="notice">{error}</p>}
 <p>Remetente da clínica: <strong>{gmailSender}</strong>.</p>
 <p>{!p.auth?'Entre com a sua conta profissional para consultar o estado da ligação.':checking?'A verificar a ligação Gmail…':!status?'Não foi possível verificar a ligação.':status.gmailConnected?'A conta Gmail da clínica está ligada.':status.gmailReady?'A ligação está preparada. A direção precisa de autorizar a conta Gmail da clínica.':'A ligação Gmail aguarda a configuração Google da aplicação.'}</p>
 {p.director?<div className="actions"><Button disabled={!p.auth||busy||(!status?.gmailConnected&&!status?.gmailReady)} onClick={()=>action(status?.gmailConnected?'disconnectGmail':'connectGmail')}>{status?.gmailConnected?'Desligar o Gmail da clínica':'Ligar o Gmail da clínica'}</Button></div>:<p className="small">A direção gere a autorização do Gmail da clínica. A sua conta pessoal de calendário é ligada separadamente abaixo.</p>}
 <p className="small">A autorização permite enviar emails pela conta da clínica; a aplicação não lê a caixa de entrada. O sumário só é enviado depois de revisto e quando a terapeuta solicita a partilha com um responsável autorizado. Não precisa de criar um domínio próprio.</p>
 </Card><Card title="Calendário e teleconsulta" sub="Ligue a sua conta Google para colocar marcações no calendário e criar ligações Meet.">
 <p>{!p.auth?'Entre com a sua conta profissional para ligar o calendário.':checking?'A verificar a ligação Google…':!status?'Não foi possível verificar a ligação.':status.googleConnected?'A sua conta Google está ligada.':status.googleReady?'A ligação Google está disponível. Autorize a sua conta para começar.':'A ligação Google aguarda a configuração da conta da clínica.'}</p>
 <div className="actions"><Button disabled={!p.auth||busy||(!status?.googleConnected&&!status?.googleReady)} onClick={()=>action(status?.googleConnected?'disconnectGoogle':'connectGoogle')}>{status?.googleConnected?'Desligar a minha conta Google':'Ligar a minha conta Google'}</Button>{p.auth&&<a className="source-link" href="/api/integrations?ics=1">Descarregar agenda para Google, Apple ou Outlook</a>}</div>
 <p className="small">O ficheiro de agenda importa as marcações existentes. Para atualizar alterações, descarregue-o novamente. A sincronização Google atualiza as marcações quando seleciona o botão correspondente; alterações feitas no Google não mudam a agenda da clínica. O calendário externo mostra “Bem Crescer — Sessão”, sem notas clínicas.</p>
 {appointments.map(ap=><article className="detail-box" key={ap.id}><strong>{ap.data.date} · {ap.data.time} · {p.records.find(r=>r.id===ap.data.patientId)?.data.name||'Sessão'}</strong><p>{ap.data.context} · {ap.data.status} · {ap.data.calendarStatus||'Por sincronizar'}</p><div className="actions"><Button variant="outline" disabled={!status?.googleConnected||busy} onClick={()=>sync(ap.id,ap.version,false)}>Atualizar no calendário Google</Button>{ap.data.context==='Online'&&!['Cancelada','Falta','Remarcada','Concluída'].includes(ap.data.status)&&<Button disabled={!status?.googleConnected||busy} onClick={()=>sync(ap.id,ap.version,true)}>Criar / atualizar ligação Meet</Button>}{videoUrl(ap.data.videoUrl)&&ap.data.context==='Online'&&!['Cancelada','Falta','Remarcada','Concluída'].includes(ap.data.status)&&<a href={videoUrl(ap.data.videoUrl)} target="_blank" rel="noreferrer">Entrar na teleconsulta</a>}<Button variant="ghost" onClick={()=>p.open('appointment',ap)}>Editar marcação</Button></div>{ap.data.videoStatus&&<p className="small">Teleconsulta: {ap.data.videoStatus}</p>}</article>)}{!appointments.length&&<Empty>As próximas marcações aparecerão aqui. Pode guardar uma ligação Meet ou Zoom no formulário da marcação Online.</Empty>}
 </Card><Card title="Emails de entrada, sumários e preparação"><p>Sumários por email: {!p.auth?'estado disponível depois de entrar':checking?'a verificar':status?.emailReady?status.emailProvider==='gmail'?`envio pelo Gmail da clínica (${gmailSender})`:'serviço Resend configurado':'serviço por configurar'}.</p>{status?.emailProvider==='gmail'?<p className="small">O estado “Aceite” confirma que o Gmail aceitou o envio. Não confirma que o destinatário recebeu ou leu o email.</p>:status?.emailProvider==='resend'?<p>Confirmação da entrega Resend: {status.webhookReady?'ligação de eventos configurada':'aguarda ligação dos eventos de entrega'}.</p>:null}<p>Avisos da véspera por email: {!p.auth?'estado disponível depois de entrar':checking?'a verificar':status?.preparationEmailEnabled?'ativos para terapeutas que escolheram receber':'por ativar'}.</p><p>Os emails de entrada usam o serviço de autenticação Supabase. Ligar o Gmail para sumários não configura os emails de entrada; o SMTP e o primeiro envio para cada conta precisam de ser confirmados separadamente.</p>{p.director&&<p>Antes de enviar, complete os contactos da equipa e dos responsáveis e as autorizações de partilha. A preferência de email da véspera está na ficha de cada terapeuta.</p>}</Card></>;
}
