'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Card,Empty,usePro} from './shared';
import {videoUrl} from '@/lib/calendar';

export function Integrations(){const p=usePro(),[status,setStatus]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){if(!p.auth)return;try{const r=await fetch('/api/integrations');const j:any=await r.json();if(!r.ok)throw Error(j.error);setStatus(j);setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{load();const state=new URLSearchParams(location.search).get('google');if(state==='connected')toast.success('Conta Google ligada. Já pode sincronizar as marcações.');if(state==='failed')toast.error('A ligação Google não foi concluída. Tente novamente.');},[p.auth]);
 async function action(action:string){setBusy(true);try{const r=await fetch('/api/integrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const j:any=await r.json();if(!r.ok)throw Error(j.error);if(j.url)location.assign(j.url);else await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function sync(id:string,version:number,meet:boolean){setBusy(true);try{const r=await fetch('/api/integrations/calendar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,version,meet})});const j:any=await r.json();if(!r.ok)throw Error(j.error);toast.success(j.message||'Calendário atualizado.');p.reload();setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const appointments=p.records.filter(r=>r.kind==='appointment'&&(p.director||r.data.therapist===p.me)&&r.data.date>=p.date).sort((a,b)=>(a.data.date+a.data.time).localeCompare(b.data.date+b.data.time));
 return <><Card title="Calendário e teleconsulta" sub="Ligue a sua conta Google para colocar marcações no calendário e criar ligações Meet.">
 {error&&<p role="alert" className="notice">{error}</p>}
 <p>{!p.auth?'Entre com a sua conta profissional para ligar o calendário.':status?.googleConnected?'A sua conta Google está ligada.':status?.googleReady?'A ligação Google está disponível. Autorize a sua conta para começar.':'A ligação Google aguarda a configuração da conta da clínica.'}</p>
 <div className="actions"><Button disabled={!p.auth||!status?.googleReady||busy} onClick={()=>action(status?.googleConnected?'disconnectGoogle':'connectGoogle')}>{status?.googleConnected?'Desligar a minha conta Google':'Ligar a minha conta Google'}</Button>{p.auth&&<a className="source-link" href="/api/integrations?ics=1">Descarregar agenda para Google, Apple ou Outlook</a>}</div>
 <p className="small">O ficheiro de agenda importa as marcações existentes. Para atualizar alterações, descarregue-o novamente. A sincronização Google atualiza as marcações quando seleciona o botão correspondente; alterações feitas no Google não mudam a agenda da clínica. O calendário externo mostra “Bem Crescer — Sessão”, sem notas clínicas.</p>
 {appointments.map(ap=><article className="detail-box" key={ap.id}><strong>{ap.data.date} · {ap.data.time} · {p.records.find(r=>r.id===ap.data.patientId)?.data.name||'Sessão'}</strong><p>{ap.data.context} · {ap.data.status} · {ap.data.calendarStatus||'Por sincronizar'}</p><div className="actions"><Button variant="outline" disabled={!status?.googleConnected||busy} onClick={()=>sync(ap.id,ap.version,false)}>Atualizar no calendário Google</Button>{ap.data.context==='Online'&&!['Cancelada','Falta','Remarcada','Concluída'].includes(ap.data.status)&&<Button disabled={!status?.googleConnected||busy} onClick={()=>sync(ap.id,ap.version,true)}>Criar / atualizar ligação Meet</Button>}{videoUrl(ap.data.videoUrl)&&ap.data.context==='Online'&&!['Cancelada','Falta','Remarcada','Concluída'].includes(ap.data.status)&&<a href={videoUrl(ap.data.videoUrl)} target="_blank" rel="noreferrer">Entrar na teleconsulta</a>}<Button variant="ghost" onClick={()=>p.open('appointment',ap)}>Editar marcação</Button></div>{ap.data.videoStatus&&<p className="small">Teleconsulta: {ap.data.videoStatus}</p>}</article>)}{!appointments.length&&<Empty>As próximas marcações aparecerão aqui. Pode guardar uma ligação Meet ou Zoom no formulário da marcação Online.</Empty>}
 </Card><Card title="Emails de entrada, sumários e preparação"><p>Sumários por email: {status?.emailReady?'serviço configurado':'serviço por configurar'}.</p><p>Confirmação da entrega: {status?.webhookReady?'ligação de eventos configurada':'aguarda ligação dos eventos de entrega'}.</p><p>Avisos da véspera por email: {status?.preparationEmailEnabled?'ativos para terapeutas que escolheram receber':'por ativar'}.</p><p>Os emails de entrada são enviados pelo serviço de autenticação. A configuração e o primeiro envio para cada conta precisam de ser confirmados.</p>{p.director&&<p>Antes de enviar, complete os contactos da equipa e dos responsáveis e as autorizações de partilha. A preferência de email da véspera está na ficha de cada terapeuta.</p>}</Card></>;
}
