'use client';
import {useCallback,useEffect,useState} from 'react';
import {Card,GridTable,Pick,Badge,usePro,uid} from './shared';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Plus,Copy,RefreshCw,ShieldCheck} from 'lucide-react';
import {toast} from 'sonner';
type Member={email:string;therapist:string;enabled:number;firstAccess:string|null};
type AccessState={members:Member[];ownerEmail:string;ownerTherapist:string};
const empty=()=>({therapist:uid(),name:'',email:'',specialty:'Terapia da Fala',hours:35,startTime:'09:00',workDays:'1,2,3,4,5'});
export function TeamAccess(){
 const p=usePro(),[state,setState]=useState<AccessState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[mode,setMode]=useState('new'),[form,setForm]=useState(empty),[revoke,setRevoke]=useState<Member|null>(null);
 const load=useCallback(async()=>{try{const r=await fetch('/api/access');const j:any=await r.json();if(!r.ok)throw Error(j.error);setState(j);setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar as contas.')}},[]);
 useEffect(()=>{load()},[load]);
 const team=p.records.filter(r=>r.kind==='team'&&r.data.isTest!==true);
 async function send(payload:object){if(!p.auth){setError('Inicie sessão para gerir a equipa.');return false}setBusy(true);setError('');try{const r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j:any=await r.json();if(!r.ok)throw Error(j.error);await load();p.reload();return true}catch(e){setError(e instanceof Error?e.message:'Não foi possível guardar.');return false}finally{setBusy(false)}}
 function create(){setForm(empty());setMode('new');setOpen(true);setError('')}
 async function copy(email:string){const text='O seu acesso profissional à clínica Bem Crescer foi preparado pela clínica. Entre em '+location.origin+' com a conta '+email+'. Use Iniciar sessão e o link enviado para esse email.';try{await navigator.clipboard.writeText(text);toast.success('Instruções copiadas. Nenhuma mensagem foi enviada.')}catch{setError('Não foi possível copiar. O endereço da aplicação é '+location.origin)}}
 return <><Card title="Contas profissionais" sub="Uma conta pessoal por profissional. Cada terapeuta consulta os seus pacientes e a sua agenda." actions={<><Button variant="outline" onClick={load} disabled={busy}><RefreshCw size={16}/>Atualizar</Button><Button onClick={create} disabled={!p.auth||busy}><Plus size={16}/>Adicionar terapeuta</Button></>}>
 <p className="small"><ShieldCheck size={16} className="inline"/> Direção: {state?.ownerEmail||'A verificar'}. Pode alternar para a sua própria prática no topo do painel.</p>
 {error&&!open&&<p className="form-error" role="alert">{error}</p>}
 <GridTable heads={['Profissional','Conta','Acesso interno','Primeira entrada','Ações']} rows={team.map(t=>{const owner=t.id===state?.ownerTherapist,member=state?.members.find(m=>m.therapist===t.id&&m.enabled)||state?.members.find(m=>m.therapist===t.id);return [<div key="name"><strong>{t.data.name}</strong><small className="block">{t.data.specialty||'Especialidade por indicar'}</small></div>,owner?state?.ownerEmail:member?.email||'Por associar',<Badge key="badge">{owner?'Direção':['Inativo','Arquivado'].includes(t.data.status)?'Perfil inativo':member?.enabled?'Autorizado':member?'Revogado':'Sem conta'}</Badge>,owner?'Conta da proprietária':member?.firstAccess?new Date(member.firstAccess).toLocaleString('pt-PT',{timeZone:'Europe/Lisbon'}):'Ainda não registada',<div className="actions" key="actions"><Button variant="outline" onClick={()=>p.open('team',t)}>Ficha e horário</Button>{!owner&&(member?.enabled?<><Button variant="outline" onClick={()=>copy(member.email)}><Copy size={15}/>Instruções</Button><Button variant="ghost" onClick={()=>setRevoke(member)}>Revogar</Button></>:<Button disabled={busy} onClick={()=>{setMode('existing');setForm({...empty(),therapist:t.id,email:member?.email||t.data.email||''});setOpen(true)}}>{member?'Reativar':'Associar conta'}</Button>)}</div>]})}/>
 </Card><Card title="Entrada da equipa"><p>1. Adicione a terapeuta com o email que irá usar para entrar.</p><p>2. Copie as instruções de entrada. A terapeuta inicia sessão com o email autorizado e confirma o link recebido.</p><p>3. Atribua os pacientes, configure o horário e registe as primeiras marcações. A terapeuta entra diretamente na sua área.</p><div className="actions"><Button variant="outline" onClick={()=>p.go('patients')}>Atribuir pacientes</Button><Button variant="outline" onClick={()=>p.go('agenda')}>Agenda da equipa</Button></div></Card>
 <Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{mode==='new'?'Adicionar terapeuta':'Associar conta profissional'}</DialogTitle><DialogDescription>O perfil fica ligado a uma conta pessoal. A clínica mantém a gestão dos acessos e dos pacientes atribuídos.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();if(await send({therapist:form.therapist,email:form.email,enabled:true,...(mode==='new'?{profile:{name:form.name,specialty:form.specialty,hours:form.hours,startTime:form.startTime,workDays:form.workDays}}:{})})){setOpen(false);toast.success('Conta profissional preparada. Pode copiar as instruções de entrada.')}}}>
 <div className="form-grid">{mode==='new'&&<><label>Nome<Input value={form.name} required minLength={2} maxLength={150} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Especialidade<Pick value={form.specialty} change={(specialty:string)=>setForm({...form,specialty})} options={['Terapia da Fala','Psicologia','Psicomotricidade','Terapia Ocupacional','Educação Especial','Outra']}/></label></>}
 <label className="full">Email da conta<Input type="email" required maxLength={254} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>
 {mode==='new'&&<><label>Horas semanais<Input type="number" min={0} max={60} value={form.hours} onChange={e=>setForm({...form,hours:Number(e.target.value)})}/></label><label>Entrada prevista<Input type="time" required value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><fieldset className="full"><legend>Dias de trabalho</legend><div className="actions">{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map((label,index)=>{const value=String((index+1)%7),days=form.workDays.split(',').filter(Boolean);return <label className="check-row" key={value}><input type="checkbox" checked={days.includes(value)} onChange={e=>setForm({...form,workDays:(e.target.checked?[...days,value]:days.filter(d=>d!==value)).sort().join(',')})}/>{label}</label>})}</div></fieldset></>}
 </div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" disabled={busy||mode==='new'&&!form.workDays}>{busy?'A guardar…':'Guardar conta'}</Button></div></form></DialogContent></Dialog>
 <AlertDialog open={!!revoke} onOpenChange={v=>!v&&!busy&&setRevoke(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Revogar acesso profissional?</AlertDialogTitle><AlertDialogDescription>A conta {revoke?.email} deixará de conseguir abrir ou alterar os registos. O histórico fica preservado e poderá reativar o acesso mais tarde.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(revoke&&await send({...revoke,enabled:false})){setRevoke(null);toast.success('Acesso revogado.')}}}>Revogar acesso</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}
