'use client';
import {Card,Empty,Badge,StatGrid,usePro,fresh} from './shared';
import {Button} from '@/components/ui/button';
import {CalendarDays,FilePenLine,Clock,MessageSquare,ArrowRight} from 'lucide-react';
import {lisbonNow} from '@/lib/care';
export function TherapistDay({openSession}:{openSession:(id:string)=>void}){
 const p=usePro(),today=lisbonNow().date,patients=p.records.filter(r=>r.kind==='patient'&&r.data.status!=='Arquivado'),name=(id:string)=>patients.find(r=>r.id===id)?.data.name||'Paciente';
 const appointments=p.records.filter(r=>r.kind==='appointment'&&r.data.therapist===p.me&&r.data.date===today&&r.data.status!=='Cancelada').sort((a,b)=>a.data.time.localeCompare(b.data.time));
 const sessions=p.records.filter(r=>r.kind==='session'),pending=p.records.filter(r=>r.kind==='appointment'&&r.data.therapist===p.me&&(r.data.date<today||r.data.date===today&&r.data.time<=lisbonNow().time)&&!['Cancelada','Falta'].includes(r.data.status)&&!sessions.some(s=>s.data.appointmentId===r.id&&s.data.status==='Concluída')).sort((a,b)=>(a.data.date+a.data.time).localeCompare(b.data.date+b.data.time));
 const point=p.records.filter(r=>r.kind==='attendance'&&r.data.therapist===p.me&&r.data.date===today).sort((a,b)=>(b.data.recordedAt||b.data.time).localeCompare(a.data.recordedAt||a.data.time))[0];
 const moves=!point||point.data.type==='Saída'?['Entrada']:point.data.type==='Pausa'?['Retoma','Saída']:['Pausa','Saída'];
 const family=p.records.filter(r=>r.kind==='careNotice'&&r.data.type==='family'&&!r.data.isRead);
 return <><StatGrid items={[["Sessões hoje",appointments.length],['Pacientes ativos',patients.length],['Sumários por concluir',pending.length],['Avisos da família',family.length]]}/>
 <div className="os-two"><Card title="O meu dia" sub="Marcações e registos associados ao seu perfil." actions={<Button variant="outline" onClick={()=>p.go('agenda')}><CalendarDays size={16}/>Agenda</Button>}>
 {appointments.length?appointments.map(a=><article className="daily-appointment" key={a.id}><time>{a.data.time}<small>{a.data.duration} min</small></time><div><h3>{name(a.data.patientId)}</h3><p>{a.data.context} · {p.records.find(r=>r.id===a.data.room)?.data.name||'Local na marcação'}</p><Badge>{a.data.status}</Badge></div><Button onClick={()=>openSession(a.id)}><FilePenLine size={16}/>{sessions.some(s=>s.data.appointmentId===a.id)?'Abrir sumário':'Registar sessão'}</Button></article>):<Empty>Sem marcações para hoje. As sessões atribuídas pela clínica aparecerão aqui.</Empty>}
 </Card><div><Card title="O meu ponto" sub="Movimentos guardados com a hora de Lisboa."><p className="daily-point"><Clock size={19}/>{point?point.data.type+' às '+point.data.time:'Ainda sem entrada hoje'}</p><div className="actions">{moves.map(type=><Button key={type} disabled={p.busy||!p.auth} variant={type==='Saída'?'outline':'default'} onClick={()=>p.save(fresh('attendance',{name:type,type,therapist:p.me}),false)}>{type==='Entrada'?'Registar entrada':type}</Button>)}<Button variant="ghost" onClick={()=>p.go('attendance')}>Histórico</Button></div></Card>
 <Card title="Preparar as próximas sessões"><p>Consulte os objetivos, últimos sumários e observações da família antes da sessão.</p><Button variant="outline" onClick={()=>p.go('preparation')}>Abrir preparação <ArrowRight size={16}/></Button></Card></div></div>
 <Card title="Sumários por concluir" sub="Marcações até hoje que ainda não têm um sumário concluído.">{pending.length?pending.slice(0,12).map(a=><div className="pilot-step" key={a.id}><FilePenLine size={19}/><div><h3>{name(a.data.patientId)}</h3><p>{a.data.date} · {a.data.time} · {sessions.some(s=>s.data.appointmentId===a.id)?'Rascunho guardado':'Por registar'}</p></div><Button variant="outline" onClick={()=>openSession(a.id)}>Continuar</Button></div>):<Empty>Os sumários estão em dia.</Empty>}</Card>
 <Card title="Contacto com as famílias" sub="Só é publicado o conteúdo que revê e decide partilhar."><p>{family.length?`${family.length} aviso(s) por ler.`:'Pode consultar mensagens, pedidos de agenda e conteúdos partilhados.'}</p><Button variant="outline" onClick={()=>p.go('family')}><MessageSquare size={16}/>Área dos pais</Button></Card></>;
}
