import {z} from 'zod';
import {identity,allRecords,checkOrigin,AppError,failure} from '@/lib/server';
import {atomicSave} from '@/lib/care-server';
import {googleToken,googleEventId} from '@/lib/integrations-server';
import {calendarAppointments,googleEvent,videoUrl} from '@/lib/calendar';
export async function POST(req:Request){try{checkOrigin(req);const a=await identity(req),x=z.object({id:z.string().regex(/^[\w-]+$/).max(120),version:z.number().int().nonnegative(),meet:z.boolean().default(false)}).parse(await req.json()),rows=await allRecords(a),ap=calendarAppointments(rows,a).find(r=>r.id===x.id);if(!ap)throw new AppError('Marcação indisponível.',403);if(ap.version!==x.version)throw new AppError('A marcação mudou. Atualize a agenda.',409);const patient=rows.find(r=>r.kind==='patient'&&r.id===ap.data.patientId);if(!patient||a.role!=='director'&&patient.data.therapist!==a.therapist)throw new AppError('Acompanhamento indisponível.',403);if(x.meet&&ap.data.status==='Concluída')throw new AppError('A sessão já está concluída.');if(x.meet&&ap.data.context!=='Online')throw new AppError('Escolha o contexto Online para criar uma teleconsulta.');const token=await googleToken(a),id=await googleEventId(a,ap.id),base='https://www.googleapis.com/calendar/v3/calendars/primary/events',headers={Authorization:'Bearer '+token,'Content-Type':'application/json'};
 if(['Cancelada','Falta','Remarcada'].includes(ap.data.status)){const r=await fetch(base+'/'+id+'?sendUpdates=none',{method:'DELETE',headers,signal:AbortSignal.timeout(15000)});if(!r.ok&&![404,410].includes(r.status))throw new AppError('Não foi possível remover a marcação do calendário.',502);await atomicSave(a,{...ap,data:{...ap.data,calendarStatus:'Removido',videoUrl:'',calendarUpdatedAt:new Date().toISOString()}},ap,undefined,[{id:patient.id,version:patient.version}]);return Response.json({ok:true})}
 const previous=await fetch(base+'/'+id,{headers,signal:AbortSignal.timeout(15000)});if(!previous.ok&&previous.status!==404&&previous.status!==410)throw new AppError('Não foi possível consultar o calendário Google.',502);const exists=previous.ok,old:any=exists?await previous.json():{},event=googleEvent(ap.data,x.meet&&!old.conferenceData),body=exists?event:{...event,id};const r=await fetch(base+(exists?'/'+id:'')+'?conferenceDataVersion=1&sendUpdates=none',{method:exists?'PATCH':'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new AppError('Não foi possível sincronizar. Confirme os acessos da sua conta Google.',r.status===409?409:502);const result:any=await r.json(),link=videoUrl(result.hangoutLink||result.conferenceData?.entryPoints?.find((e:any)=>e.entryPointType==='video')?.uri),meetStatus=result.conferenceData?.createRequest?.status?.statusCode;
 await atomicSave(a,{...ap,data:{...ap.data,calendarStatus:'Sincronizado',calendarUpdatedAt:new Date().toISOString(),...(x.meet?{videoUrl:link||ap.data.videoUrl||'',videoStatus:link?'Disponível':meetStatus==='failure'?'Criação falhou':'A preparar ligação'}:{})}},ap,undefined,[{id:patient.id,version:patient.version}]);return Response.json({ok:true,meetStatus:link?'Disponível':meetStatus||'',message:x.meet&&!link?'O Google está a preparar a ligação. Volte a sincronizar para a consultar.':'Marcação sincronizada.'});
}catch(e){return failure(e)}}
